### ISSUE TITLE
po4a.org

### ISSUE THREAD

**Issue by brandelune** [mquinson/po4a#108]
The site still lists the alioth server as the dev list host.

**Comment by mquinson** [comment]
I think I just fixed it. Could you please confirm or be more specific?

Thanks, Mt.

**Comment by mquinson** [comment]
Ok, I really think I fixed this, thus closing. If I forgot a mention, do not hesitate to reopen (with more info).

**Comment by brandelune** [comment]
Sorry for the silence. Yes, it's fixed. Thank you.

**Comment by mquinson** [comment]
Don't be sorry. I was in a po4a rush after months of inactivity on po4a...
