### ISSUE TITLE
po4a-devel not migrated to new server

### ISSUE THREAD

**Issue by brandelune** [mquinson/po4a#110]
https://alioth-lists.debian.net/cgi-bin/mailman/listinfo

The po4a-devel list is not listed there.

**Comment by bexelbie** [comment]
The mailing list is moving to the po4a.org domain.  The migration will happen on 2018-04-23 (next Monday) and start at 10:30 JST.

**Comment by bexelbie** [comment]
I've created a PR to update the site.  Mind being a second pair of eyes reading it?

https://github.com/mquinson/po4a-website/pull/6

**Comment by bexelbie** [comment]
The site has been updated.
