### ISSUE TITLE
Release tarball for 0.53?

### ISSUE THREAD

**Issue by l2dy** [mquinson/po4a#115]
Hi,

At MacPorts we were building po4a from tarballs released on alioth. Now that po4a moved to GitHub, should we switch to GitHub-generated archives and ignore the following warning, or will a properly generated tarball be uploaded somewhere?

```
/opt/local/bin/perl5.26 Build.PL installdirs=core --config cc="/usr/bin/clang" --config ld="/usr/bin/clang"
WARNING: the following files are missing in your kit:
	META.yml
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'po4a' version '0.53'
```

**Comment by mquinson** [comment]
Hello,

I just added a source tarball as if it were a binary release. Would it fit your needs?

Thanks,

**Comment by l2dy** [comment]
Thanks a lot! GitHub-generated tarballs may stealthily change due to git updates [[1]] so static tarballs are much appreciated.

I've updated po4a in MacPorts in https://github.com/macports/macports-ports/commit/b77ae2b56e586485479cafe64e605c9775a35327.

[1]: https://trac.macports.org/ticket/54839
