### ISSUE TITLE
Please push a new version

### ISSUE THREAD

**Issue by jnavila** [mquinson/po4a#12]
Apart from the bug in literal paragraphs (which can be overriden by just putting the right formatting in the translated string), there is an urgent need for a tagged up to date version of po4a able to correctly manage empty attributes in asciidoc.

Right now, the lack of proper version is preventing from proposing a patch series for the translation of manpages of the Git project.

Thank you.

**Comment by mquinson** [comment]
I'm on it. 

Thank you for keeping po4a alive.

**Comment by mquinson** [comment]
Done. There still many bug to fix, but  the release is out. Thanks for the nudge.
