### ISSUE TITLE
Several lists of modules are not consistent

### ISSUE THREAD

**Issue by mquinson** [mquinson/po4a#136]
I have the feeling that the list of modules are not consistent nor accurate. I'd really appreciate if someone could double check that. We have one on the website, one in the README.md and one in the doc somewhere (can't remember where exactly).

Also, one should check whether these lists are accurate wrt to the actual list of modules that we have under lib/Locale/Po4a. Some modules (such as the text module) serve as an umbrella to several sub-types (such as fortune for the text module). It'd be excellent if the lists could show that too.

Thanks in advance,

**Comment by mquinson** [comment]
I see:
 - the webpage: https://github.com/mquinson/po4a-website/blob/master/src/index.php.en#L42
 - the README: https://github.com/mquinson/po4a/blob/master/README.md
 - the po4a(7) manpage: https://github.com/mquinson/po4a/blob/master/doc/po4a.7.pod#supported-formats

Unifying their format would indeed help to maintain them, and that should be done :)
I see this issue as a good entry point for newcomers, and I think that seasoned developers should leave it alone, please.

**Comment by bexelbie** [comment]
Thanks for catching the third one.  I agree that this is a great beginner task.  It is Hacktober after all :)

**Comment by mquinson** [comment]
These list should also be compared to the list of installed modules in the tarball:
 - [ ] https://github.com/mquinson/po4a/blob/master/MANIFEST#L17
