### ISSUE TITLE
WML module removes comments at the beginning of a file

### ISSUE THREAD

**Issue by toddy15** [mquinson/po4a#138]
While rewriting the test suite, I discovered that the output of 22-wml.t actually fails the test. This has not been discovered earlier, because the test command to check the output was incorrect. :-(

It used "compare-po.pl" instead of a normal "diff", so the content of the files have not been compared at all, because compare-po.pl skips everything up until the first "msgid", which is not found in the output file. Therefore, effectively zero lines are compared.

This is now fixed, but it discovered a long standing bug in the WML module.

The test has been marked as TODO.

**Comment by mquinson** [comment]
Thanks for that, tobias, that's a very good change. Again ;)
