### ISSUE TITLE
Website not displayed in Brazilian Portuguese by default

### ISSUE THREAD

**Issue by rffontenelle** [mquinson/po4a#139]
The website [po4a.org](https://po4a.org) is not automatically being displayed in my native language, Brazilian Portuguese (pt_BR), even though my browser is correctly set to Brazilian Portuguese and the documentation is 100% translated and available for selection. When Portuguese (pt, from Portugal) translation is available, pages are being displayed in this language; on the other side, when there is no Portuguese translation, English page is displayed.

I can only see pages in Brazilian Portuguese if I select such language ("Português (Brasil)") in the bottom of the website, then the URL gets suffixed with '.pt_BR' (e.g. index.php.pt_BR). Even when I do this, every link I click will return to the original language (as explained in the above paragraph).

An example: I access: https://po4a.org/man/index.php. I see this page in Portuguese from Portugal (msguntypot(1) has description "atualização de ficheiros PO quando um erro de digitação foi corrigido no ficheiro POT" -- "ficheiro" is (for me) clearly a Portuguese translation). If I select "Português (Brasil)" from bottom of the page, it changes to Brazilian Portuguese and the URL changes to https://po4a.org/man/index.php.pt_BR;  on the other side, the main page of the website (https://po4a.org/) I see in English (there is no Portuguese translation), changing to Brazilian Portuguese when I click in the "Português (Brasil)" from bottom of the page.

Environment:
- Distro: Arch Linux 64-bit
- Browser: Chromium, Firefox (Brazilian Portuguese UI installed, also preferred language)

Can this please be fixed?

**Comment by mquinson** [comment]
I have noticed this problem, but I'm puzzled about how to fix it. I'm very very far from being a web guy. Any kind of help would be greatly welcome, even if it implies a patch completely rewriting how the web site is translated (as long as we don't loose the existing translations).

**Comment by mquinson** [comment]
Indeed, your solution solved the problem for me. Well. I also had a configuration error and I added a link to the Debian website explanation of how to properly configure your firefox.

**Comment by mquinson** [comment]
Thanks for the bug report and for the fix ;)
