### ISSUE TITLE
Build issue "Died at Po4aBuilder.pm line 161"

### ISSUE THREAD

**Issue by AngryPenguinPL** [mquinson/po4a#142]
Hi.
I tried to build rpm package with a new version of po4a - 54.

When I used source file, then I see this issue with missing [Meta file issue 115](https://github.com/mquinson/po4a/issues/115). 

So I try with tarball and when build I see this:

```
+ perl Build.PL installdirs=vendor
DEBUG util.py:499:  Created MYMETA.yml and MYMETA.json
DEBUG util.py:499:  Creating new 'Build' script for 'po4a' version '0.54'
DEBUG util.py:499:  + ./Build
DEBUG util.py:499:  Created META.yml and META.json
DEBUG util.py:497:  BUILDSTDERR: Unknown format type: pod.
DEBUG util.py:497:  BUILDSTDERR: List of valid formats:
DEBUG util.py:497:  BUILDSTDERR:   - asciidoc: AsciiDoc format.
DEBUG util.py:497:  BUILDSTDERR:   - dia: uncompressed Dia diagrams.
DEBUG util.py:497:  BUILDSTDERR:   - docbook: DocBook XML.
DEBUG util.py:497:  BUILDSTDERR:   - guide: Gentoo Linux's XML documentation format.
DEBUG util.py:497:  BUILDSTDERR:   - ini: INI format.
DEBUG util.py:497:  BUILDSTDERR:   - kernelhelp: Help messages of each kernel compilation option.
DEBUG util.py:497:  BUILDSTDERR:   - latex: LaTeX format.
DEBUG util.py:497:  BUILDSTDERR:   - man: Good old manual page format.
DEBUG util.py:497:  BUILDSTDERR:   - pod: Perl Online Documentation format.
DEBUG util.py:497:  BUILDSTDERR:   - rubydoc: Ruby Documentation (RD) format.
DEBUG util.py:497:  BUILDSTDERR:   - sgml: either DebianDoc or DocBook DTD.
DEBUG util.py:497:  BUILDSTDERR:   - texinfo: The info page format.
DEBUG util.py:497:  BUILDSTDERR:   - tex: generic TeX documents (see also latex).
DEBUG util.py:497:  BUILDSTDERR:   - text: simple text document.
DEBUG util.py:497:  BUILDSTDERR:   - wml: WML documents.
DEBUG util.py:497:  BUILDSTDERR:   - xhtml: XHTML documents.
DEBUG util.py:497:  BUILDSTDERR:   - xml: generic XML documents (see also docbook).
DEBUG util.py:497:  BUILDSTDERR:   - yaml: YAML documents.
DEBUG util.py:497:  BUILDSTDERR: Died at Po4aBuilder.pm line 161.
DEBUG util.py:497:  BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.zBgf15 (%build)
DEBUG util.py:497:  BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.zBgf15 (%build)
DEBUG util.py:499:  RPM build errors:
DEBUG util.py:640:  Child return code was: 1
INFO util.py:556:  EXCEPTION: [Error()]
```

Dont know how to build it correctly. Any ideas?

Here is [full build log](http://file-store.openmandriva.org/api/v1/file_stores/b8ea57505e189ea5839a86f02fd33cbbf03546d9.log?show=true)
Here is [spec](https://github.com/AngryPenguinPL/po4a/blob/AngryPenguinPL-testing/po4a.spec)

Maybe I missed something required to build?

**Comment by mquinson** [comment]
Mmm, thanks for the report, even if it shows my unability to write a decent build file. I tried to have a look, and it seems that a full rewrite (merging Po4aBuilder into Build.PL) would simplify greatly this stuff.

Any pull request would be welcome...

**Comment by berolinux** [comment]
The missing META.yml is probably unrelated, I've seen that on a successful build as well (META.yml seems to be autogenerated later).

This fragment is more interesting:
DEBUG util.py:497:  BUILDSTDERR: Unknown format type: pod.
DEBUG util.py:497:  BUILDSTDERR: List of valid formats:
[...]
DEBUG util.py:497:  BUILDSTDERR:   - pod: Perl Online Documentation format.

Looks like pod support is not detected even though it is there.

From a quick look, I think the problem is a missing explicit dependency on the Pod::Parser perl module. It's used by Pod.pm, but the error from its absence is caught and replaced with the confusing message.

**Comment by berolinux** [comment]
https://github.com/mquinson/po4a/pull/143
