### ISSUE TITLE
Please help how to migrate from po4a-build to something else

### ISSUE THREAD

**Issue by josch** [mquinson/po4a#144]
Hi,

in Debian we have two packages that fail to build from source because of the removal of po4a-build:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906386
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906412

I never used po4a before. Could you quickly advise how to best replace `po4a-build` and `po4a-build --pot-only` with the remaining tools from po4a?

Thanks!

cheers, josch

**Comment by ciampix** [comment]
Mmm devs removed the po4a-build utility under the assumption that nobody was using it. Perhaps this decision was too hasty? How about to re-add it?

**Comment by mquinson** [comment]
I'm sorry I didn't found these projects before I decided to remove po4a-build. I searched the internet and sources.debian.net for projects using po4a-build, but failed to find any... My mistake.

As for re-adding po4a-build, I'd really like to avoid, as nobody understands how it works, and it's not maintained for ages. 

The best solution is certainly to provide a replacement po4a.cfg for @josch to use in place of the existing config. But unfortunately, with the new term beginning, I have absolutely no time to do this myself for at least 2 weeks. Could somebody have a look a this? @ciampix maybe? ;)

**Comment by ciampix** [comment]
Well it seems that the assumption that there was not ***active*** packages using po4a-build anymore still apply after all... if this is the case it could be a classic won't-fix ...

**Comment by josch** [comment]
Yes, that assumption still holds and I'm not arguing that po4a-build should be re-added.

This issue is merely a call for help so that we can keep those two packages still alive despite po4a-build having been removed.

**Comment by ciampix** [comment]
Ok ... the thing is that po4a-build is something that should help automatize po4a single commands run (a sort of "make" but just for .po files), so, in theory you can avoid it entirely if you know what you want to do.
Having said so, how can I help you?

**Comment by josch** [comment]
For example in case of multistrap, we have this Makefile:

https://sources.debian.org/src/multistrap/2.2.9/Makefile/

It calls po4a-build. I never used po4a, so I'm at a loss about with what to replace that line to let it output the exact same thing that po4a-build did before.

In the same directory as the Makefile there is a po4a-build.conf which might be relevant:

https://sources.debian.org/src/multistrap/2.2.9/po4a-build.conf/

**Comment by mquinson** [comment]
As @osamuaoki, converting these files should not be very difficult, but these two packages are not maintained anymore. They were fixed the harsh way: the po4a-build script was copied over. I think that this solves the issue very efficiently, even if not nicely...

**Comment by ciampix** [comment]
@mquinson you mean in the git repo? There are still a lot of references of po4a-build in po4a docs. If it is missing then docs should be edited accordingly. Still the easiest solution is to leave it where it is for the time being waiting for someone who could see it through...

**Comment by mquinson** [comment]
Good point, @ciampix, I didn't check it either :/
But I fail to find any reference to that tool in our doc: `git grep po4a-build` does not triggers anything useful, AFAIK.
Could you please point me to these references?

**Comment by ciampix** [comment]
Yes I did the same and found anything either but ... is it possible that po4a calls po4a-build? Because I see a lot of:
> po4a po4a.cfg
Is po4a.cfg read by po4a-build?

**Comment by ciampix** [comment]
May I ask why po4a-build and its docs were removed from the sources? Did they give some error or problems of any kind?

**Comment by mquinson** [comment]
Actually I don't plan to reintroduce po4a-build. This bash script was duplicating the features of the main po4a script, only worse. I think that everything you could do in po4a-build can be done in `po4a`, that is better integrated with everything.
This is why I removed po4a-build a while ago. I'm closing this bug again, but feel free to reopen if you spot some missing bits.
