### ISSUE TITLE
Suppress "The amount of entries differ between files: Y is not X"

### ISSUE THREAD

**Issue by ip1981** [mquinson/po4a#156]
I'd like to suppress _"The amount of entries differ between files: Y is not X"_ where Y > X, when invoking `po4a-translate`.

Here is the use case:

1. `po4a-updatepo` allows updating one PO file with many original (untranslated) files, e. g. ` po4a-updatepo -f xhtml -M utf8 -m _site/en/about.html -m _site/en/archive.html -m _site/en/contact.html -m _site/en/index.html -m _site/en/posts/2015-08-12-spqr.html -m _site/en/posts/2015-10-07-rosa-rosa-rosam.html -m _site/en/posts/2015-11-28-carpe-diem.html -m _site/en/posts/2015-12-07-tu-quoque.html -p po/ru.po`.
2. Then I use `po4a-tranlate` to translate individual files. I think this is the only way to do so (according to the man page). Anyway, in my case I can only translate one file at a time.
3. Unfortunately, the number of to-be-translated strings in the original file is much less than in the PO file. Hence the confusing message.

Having a single PO file for many original (untranslated) file is a very useful feature for translators (more context), also it de-duplicates common strings in many files, especially useful in static WWW sites where each page follows the same template with headers, footers, etc.

Example PO:

```po
#. type: Attribute 'lang' of: <html>
#: _site/en/about.html:2 _site/en/archive.html:2 _site/en/contact.html:2
#: _site/en/index.html:2 _site/en/posts/2015-08-12-spqr.html:2
#: _site/en/posts/2015-10-07-rosa-rosa-rosam.html:2
#: _site/en/posts/2015-11-28-carpe-diem.html:2
#: _site/en/posts/2015-12-07-tu-quoque.html:2
msgid "en"
msgstr "ru"
#...
#. type: Content of: <html><body><main><h1>
#: _site/en/archive.html:23
msgid "Archives"
msgstr "Архив"
#...
#. type: Content of: <html><body><footer>
#: _site/en/about.html:33 _site/en/archive.html:49 _site/en/contact.html:28
#: _site/en/index.html:59 _site/en/posts/2015-08-12-spqr.html:41
#: _site/en/posts/2015-10-07-rosa-rosa-rosam.html:43
#: _site/en/posts/2015-11-28-carpe-diem.html:41
#: _site/en/posts/2015-12-07-tu-quoque.html:43
msgid ""
"Site proudly generated by <a href=\"http://jaspervdj.be/hakyll\">Hakyll</a>"
msgstr ""
"Сайт создан с помощью <a href=\"http://jaspervdj.be/hakyll\">Hakyll</a>"
```

**Comment by mquinson** [comment]
Hello Igor, thanks for this feedback.
I'm wondering: is this warning really a warning, or does it prevent the work from being done? In the former case, this should be fixed ASAP, but in the latter case, this is probably less critical.

Thanks,

**Comment by ip1981** [comment]
Oh, it is just a warning, it does not prevent translation.

**Comment by mquinson** [comment]
Hello,
sorry for the very long delay here. My personal advise would be to go for the full po4a binary instead of using `po4a-translate`. The later script is much more limited indeed.

**Comment by mquinson** [comment]
I'm closing this issue because the more I think about it, the more I dislike the idea of removing a warning that is useless but harmless in the scenario that you describe while it could be very useful in other scenarios (ie, when there is actually an issue).

**Comment by ip1981** [comment]
> it could be very useful in other scenarios (ie, when there is actually an issue).

Out of curiosity, do you know of any such scenario?

And after all, I think there is not just inconvenience, but internal inconsistency: there is a legit scenario when data (translations) is created and another legit scenario when the data is used, but the first causes a warning in the second :)

**Comment by mquinson** [comment]
Hello,

I think that this can happen when you use the wrong pot file for your translation, couldn't it?

**Comment by ip1981** [comment]
> I think that this can happen when you use the wrong pot file for your translation, couldn't it?

There will be much more louder errors like "only 5% translated, rejecting", won't it? :)

**Comment by mquinson** [comment]
Shit, you're right :)
