### ISSUE TITLE
markdown parser fails to preserve fenced code blocks

### ISSUE THREAD

**Issue by jonassmedegaard** [mquinson/po4a#157]
Hi,

Markdown (mode of Text) parser wreaks havoc on fenced code blocks.

Please consider adopting my slight fork addressing that, available at https://salsa.debian.org/js/po4a

(sorry for the slight inconvenience of not offering it here: I will not push code to Github - only engage in issue trackers - due to their terms of service potentially watering down copyleft licensed code).

**Comment by jonassmedegaard** [comment]
NB! Above changeset also includes my fix for issue #158 - in case for some reason you don't want to adopt that.

**Comment by mquinson** [comment]
What about proposing a MR on salsa, then? https://salsa.debian.org/mquinson/po4a

**Comment by mquinson** [comment]
Can it be that your project on salsa is closed and not public? It's not to be found on salsa: https://salsa.debian.org/search?utf8=%E2%9C%93&search=po4a

**Comment by jonassmedegaard** [comment]
Quoting Martin Quinson (2018-11-01 18:15:33)
> Can it be that your project on salsa is closed and not public? It's 
> not to be found on salsa: 
> https://salsa.debian.org/search?utf8=%E2%9C%93&search=po4a

Sorry - should be accessible now!

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by toddy15** [comment]
Hi Jonas,

I've just looked at your fork on salsa -- it seems that there's only the copyright line included, I cannot see anything for the markdown parser. Is that change still included?

Regards,
Tobias

**Comment by jonassmedegaard** [comment]
Quoting Dr. Tobias Quathamer (2018-11-03 13:50:24)
> I've just looked at your fork on salsa -- it seems that there's only 
> the copyright line included, I cannot see anything for the markdown 
> parser. Is that change still included?

Sorry for not mentioning here.  You guessed correctly that it is not 
included: You requested a PR for the copyright line alone, and 
apparently Gitlab can only fork to a git by same name so I replaced this 
changeset by the minimal licensing fix, and when that is solved we can 
move on to this larger one.

If you know of a better approach (except using Github) then I am open to 
suggestions - I am not fluent in doing PRs.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by toddy15** [comment]
Ah, OK. Well, the copyright line is now included in git, so you may switch your fork back to the larger markdown patch.

**Comment by jonassmedegaard** [comment]
Quoting Dr. Tobias Quathamer (2018-11-03 13:50:24)
> I've just looked at your fork on salsa -- it seems that there's only 
> the copyright line included, I cannot see anything for the markdown 
> parser. Is that change still included?

Please look again now: Git with only copyright changeset has been 
replaced with git containing markdown changeset - based on upstream code 
as of today.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by mquinson** [comment]
Hello,

On Sat, Nov 03, 2018 at 06:47:47AM -0700, Jonas Smedegaard wrote:
> 
> If you know of a better approach (except using Github) then I am open to 
> suggestions - I am not fluent in doing PRs.

I'm very aware of the issues with github, and I moved most of my
projects out of there, but we just moved po4a from alioth to github,
and I fear that we could break the momentum by moving again so soon.
This is the only reason why we're still on github, I think. For the
time being, we maintain a fork synchronized on salsa.d.o specifically
for the ones who don't want to use github. 

So, the best move for you is to fork the project on salsa and forget
about github. Then, it would be wonderful if you could learn about MR
(Merge Requests -- that's how gitlab calls PR Pull Request). Github
new TOS are concerning, but the workflow they invented is really
great. We are really lucky that gitlab pushed this further.

Cheers,
Mt.

**Comment by jonassmedegaard** [comment]
Quoting Jonas Smedegaard (2018-11-03 16:26:49)
> Quoting Martin Quinson (2018-11-03 15:44:04)
> > On Sat, Nov 03, 2018 at 06:47:47AM -0700, Jonas Smedegaard wrote:
> > > 
> > > If you know of a better approach (except using Github) then I am 
> > > open to suggestions - I am not fluent in doing PRs.
> > 
> > I'm very aware of the issues with github, and I moved most of my 
> > projects out of there, but we just moved po4a from alioth to github, 
> > and I fear that we could break the momentum by moving again so soon. 
> > This is the only reason why we're still on github, I think. For the 
> > time being, we maintain a fork synchronized on salsa.d.o specifically 
> > for the ones who don't want to use github.
> > 
> > So, the best move for you is to fork the project on salsa and forget 
> > about github. Then, it would be wonderful if you could learn about MR 
> > (Merge Requests -- that's how gitlab calls PR Pull Request). Github 
> > new TOS are concerning, but the workflow they invented is really 
> > great. We are really lucky that gitlab pushed this further.
> 
> Where on Salsa?
> 
> I see only https://salsa.debian.org/debian/po4a which seems to not 
> contain upstream git commits - only upstream release tarball imports.

Ah, if you mean that there are no fork at Salsa maintained by you, but 
you encourage me to create one from scratch, syncronized with upstream 
git at Github, then I believe that is _exactly_ what I have done now.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by mquinson** [comment]
----- Le 3 Nov 18, à 16:26, Jonas Smedegaard <notifications@github.com> a écrit : 

> Quoting Martin Quinson (2018-11-03 15:44:04)
> > For the
> > time being, we maintain a fork synchronized on salsa.d.o specifically
> > for the ones who don't want to use github.

> > So, the best move for you is to fork the project on salsa and forget
> > about github. Then, it would be wonderful if you could learn about MR
> > (Merge Requests -- that's how gitlab calls PR Pull Request). Github
> > new TOS are concerning, but the workflow they invented is really
> > great. We are really lucky that gitlab pushed this further.

> Where on Salsa?

> I see only https://salsa.debian.org/debian/po4a which seems to not
> contain upstream git commits - only upstream release tarball imports.

https://salsa.debian.org/search?utf8=%E2%9C%93&search=po4a 

The third one, not the fourth one. More specifically: 
https://salsa.debian.org/mquinson/po4a 

Mt

**Comment by jonassmedegaard** [comment]
Quoting Martin Quinson (2018-11-03 18:19:20)
> ----- Le 3 Nov 18, à 16:26, Jonas Smedegaard <notifications@github.com> a écrit : 
> 
> > Quoting Martin Quinson (2018-11-03 15:44:04)
> > > For the
> > > time being, we maintain a fork synchronized on salsa.d.o specifically
> > > for the ones who don't want to use github.
> 
> > > So, the best move for you is to fork the project on salsa and forget
> > > about github. Then, it would be wonderful if you could learn about MR
> > > (Merge Requests -- that's how gitlab calls PR Pull Request). Github
> > > new TOS are concerning, but the workflow they invented is really
> > > great. We are really lucky that gitlab pushed this further.
> 
> > Where on Salsa?
> 
> > I see only https://salsa.debian.org/debian/po4a which seems to not
> > contain upstream git commits - only upstream release tarball imports.
> 
> https://salsa.debian.org/search?utf8=%E2%9C%93&search=po4a 
> 
> The third one, not the fourth one. More specifically: 
> https://salsa.debian.org/mquinson/po4a 

Thanks.

Perhaps I was not at the front page when I searched, and that is 
required to locate personal git repos.

Re-pushed my changeset, now linked to yours, and did an MR:
https://salsa.debian.org/mquinson/po4a/merge_requests/72


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by toddy15** [comment]
Am 03.11.2018 um 18:50 schrieb Jonas Smedegaard:
> Thanks.
> 
> Perhaps I was not at the front page when I searched, and that is
> required to locate personal git repos.
> 
> Re-pushed my changeset, now linked to yours, and did an MR:
> https://salsa.debian.org/mquinson/po4a/merge_requests/72

Hi,

thanks a lot for this, I've merged it on github. The MR on salsa could
now be closed. Sorry for the inconvenience of not doing this automatically.

Regards,
Tobias

**Comment by mquinson** [comment]
Hello @toddy15, thanks for taking care of this. Next time, if you prefer,  you could simply comment on the pull request saying that it looks good to you, and I'll click for you and resynchronize the repos.
Another possibility, of course, would be that you request an account on salsa to become an official contributor of that project too ;)
Anyway. Thanks again for taking care of this. I just had to push the commits you integrated to salsa to get the MR closed automatically.

**Comment by toddy15** [comment]
Sorry to have caused more work for you. I am on salsa, BTW, my username is toddy. :-)

**Comment by mquinson** [comment]
You did not cause more work. To the contrary: you did the review, and I had a git pull + a git push to do. That's perfect, thanks.
You're added to salsa now.
