### ISSUE TITLE
please credit me for my contributed markdown parser

### ISSUE THREAD

**Issue by jonassmedegaard** [mquinson/po4a#158]
Hi,

Many years ago I contributed the markdon mode of the Text parser to this project.  I notice now that I am not credited for that, and would appreciate if that would be corrected (blame is arguably on myself of not including a copyright statement in my contributed patches back then).

E.g. adopt this: https://salsa.debian.org/js/po4a/commit/28ae7e4

**Comment by mquinson** [comment]
Hello Jonas, 

I'm really sorry to learn that I forgot to credit you for your work. Please be assured that this is a stupid mistake from my side, not a decision.
The URL that you give is a 404 here, but that's not important. I feel stupid for my mistake.

Could you please prepare a PR that we could use to close this issue?

Thanks in advance, Mt

**Comment by jonassmedegaard** [comment]
Quoting Martin Quinson (2018-11-01 18:12:49)
> I'm really sorry to learn that I forgot to credit you for your work. 
> Please be assured that this is a stupid mistake from my side, not a 
> decision.
> The URL that you give is a 404 here, but that's not important. I feel 
> stupid for my mistake.
> 
> Could you please prepare a PR that we could use to close this issue?

As I wrote before, no blame here: I provided a patch which it seems 
passed through multiple hands before it landed in the project.

I am just happy to have this corrected now that I pour a bit of 
attention to it myself again :-)

Access to the git should work now.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by toddy15** [comment]
Hi,

I've cherry-picked the commit from your repository on salsa.d.o.

Regards,
Tobias

**Comment by jonassmedegaard** [comment]
Quoting Dr. Tobias Quathamer (2018-11-03 13:45:20)
> I've cherry-picked the commit from your repository on salsa.d.o.

Thanks!

I'll then drop that and replace with my markdown changeset.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
