### ISSUE TITLE
Support for ITS (Internationalization Tag Set)

### ISSUE THREAD

**Issue by mquinson** [mquinson/po4a#16]
ITS is a standard from the W3C on how to make XML translatable. It would be interesting to support this. 

A good starting point is [itstools](http://itstool.org/) ([code on github](https://github.com/itstool/itstool)). The project seems rather dormant right now, but they provide a large amount of tests that we could borrow. Plus, this tool seem to be used by the whole Gnome community...

**Comment by Fat-Zer** [comment]
Note that there could be formal license problems about borrowing: itstools is GPL-3+ and po4a is GPL-2...

**Comment by mquinson** [comment]
@Fat-Zer: Of course you are right. Actually, I was more thinking of using their test suite to validate our tools than to reuse their code, since this tool is coded in python. They also include a testsuite from the W3C that may be more suitable for inclusion in our codebase, maybe.

The more I think about it, and the more I think that their approach is probably more adapted and much more robust than the trick that we are currently leveraging in the Xml module.

**Comment by mquinson** [comment]
Closing this issue because it's better to develop a new module when someone actually needs it, not only when it seems easy to implement.
