### ISSUE TITLE
Translate or not a text block by po-debiandoc modules

### ISSUE THREAD

**Issue by rffontenelle** [mquinson/po4a#161]
The text block below is part of [po4a.7.pod](/mquinson/po4a/blob/master/doc/po4a.7.pod) since po4a version 0.13.5 or before, and it is stated that the `po-debiandoc` introduces to PO files.

AFAIK, the `po-debiandoc` tool is deprecated and unavailable for some time (I particularly didn't came across with it before), so I can't tell where it gets this text block and if it was translatable or not.

Does anyone can tell whether this should be translated or not?

```
... That's why the PO files produced by the po-debiandoc module
contain the following header:

 #
 #  ADVISES TO DEVELOPERS:
 #    - you do not need to manually edit POT or PO files.
 #    - this file contains the translation of your debconf templates.
 #      Do not replace the translation of your program with this !!
 #        (or your translators will get very upset)
 #
 #  ADVISES TO TRANSLATORS:
 #    If you are not familiar with the PO format, gettext documentation
 #     is worth reading, especially sections dedicated to this format.
 #    For example, run:
 #         info -n '(gettext)PO Files'
 #         info -n '(gettext)Header Entry'
 #
 #    Some information specific to po-debconf are available at
 #            /usr/share/doc/po-debconf/README-trans
 #         or http://www.debian.org/intl/l10n/po-debconf/README-trans
 #
```

**Comment by rffontenelle** [comment]
po4a doesn't seem to allow marking string not-for-translation (#77), but maybe this string could have a comment for translators that is extracted to the PO file instructing to not translate.  If it shouldn't be translated, I mean.

**Comment by mquinson** [comment]
The easiest to fix this bug is probably to reword this paragraph. Instead of a verbatim of the venerable po-debiandoc output, we could simply paraphrase the same content in a more conventional way.
As usual, help is welcome. PR are really appreciated :)

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by MetalDent** [comment]
Hi @mquinson  , in what way can we explain this deprecation?

**Comment by mquinson** [comment]
@MetalDent I don't understand your question. Which deprecation ?

**Comment by MetalDent** [comment]
@mquinson , according to @rffontenelle `po-debiandoc` tool is deprecated, is that right?

**Comment by mquinson** [comment]
This string was removed from the documentation, thus closing.
