### ISSUE TITLE
Minor issue in po4a-build.conf(5) or in po4a-build itself

### ISSUE THREAD

**Issue by Fat-Zer** [mquinson/po4a#17]
The documentation for DOCBOOKDIR seems a bit erroneous:

[doc/po4a-build.conf.5.pod](https://github.com/mquinson/po4a/blob/master/doc/po4a-build.conf.5.pod) says:
```
=item DOCBOOKDIR

Similar to XMLDIR but only used to prepare the translated DocBook files. If
your package wants to use .sgml files, please discuss how these should be
built on the po4a-devel mailing list.

 # pattern to find the .docbook files
 DOCBOOKDIR=""
```
So According to first paragraph it is expected that its value should something like: DOCBOOKDIR="share/docbook"
But according to comment it the example it should be "share/docbook/*.docbook" (or whatever extension).

Also according to the content of po4a-build:
```
if [ -n "$XMLDIR" ]; then
	for file in $XMLDIR/*.xml; do
		LOCAL=`basename $file`
		wrap_langs "[type:docbook]" "$file" "\$lang:$XMLDIR/\$lang/$LOCAL"
	done
fi
if [ -n "$DOCBOOKDIR" ]; then
	for file in $DOCBOOKDIR; do
		LOCAL=`basename $file`
		wrap_langs "[type:docbook]" "$file" "\$lang:$BASEDIR/\$lang/$LOCAL"
	done
fi
```
So DOCBOOKDIR is expected to match the second one variant.

All in all I suggest to either update the script to make it behave according to docs or to fix up the docs themself.

**Comment by mquinson** [comment]
@dbarbier are you the original author of po4a-build, maybe? I personnally don't have any strong idea about how to solve that issue.

Kudos to @Fat-Zer for this great bug report!

**Comment by Fat-Zer** [comment]
I'm just translating docs right now... I know it's silly, but I can't get myself over an issue... =))

**Comment by mquinson** [comment]
po4a-build(1) seems somewhat redundent with po4a(1). A quick search on https://sources.debian.net seems to imply that nobody's using po4a-build (because no configuration file can be found), so I am considering removing po4a-build all together.

Any strong feeling here?

**Comment by ciampix** [comment]
I have to admit I never used it. I though for my lack of knowledge about it. Are there any examples of use of it? Reasons why it should be used instead of the mere po4a command?

**Comment by bexelbie** [comment]
+1 for removal
