### ISSUE TITLE
"Unexpected closing tag" on <source> HTML5 tag

### ISSUE THREAD

**Issue by sajolida** [mquinson/po4a#179]
When processing the following valid HTML5 snippet, po4a returns an "Unexpected closing tag </video> found":

<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en" dir="ltr" xmlns="http://www.w3.org/1999/xhtml"&gt;
&lt;head&gt;
&lt;title&gt;Video</title>
&lt;/head&gt;
&lt;body class="en"&gt;
&lt;video width="640" height="360" poster="https://tails.boum.org/install/inc/videos/boot-menu-key.png"&gt;
  &lt;source src="https://tails.boum.org/install/inc/videos/boot-menu-key.webm" type="video/webm"&gt;
&lt;/video&gt;
&lt;/body&gt;
</pre>

Replacing, in the <source> tag, the closing ">" with " />" works around this easily but I don't think that it should be required:

* This snippet passes the W3C validator: https://validator.w3.org/nu/#textarea
* It's a copy of the snippet provided in the Mozilla dev doc: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

I tried with both po4a 0.47-2 (Debian Stretch) and 0.55-1 (Debian Buster).

**Comment by eighthave** [comment]
What if you make it a properly closed HTML tag, e.g.:

```diff
 <!DOCTYPE html>
 <html lang="en" dir="ltr" xmlns="http://www.w3.org/1999/xhtml">
 <head>
 <title>Video</title>
 </head>
 <body class="en">
 <video width="640" height="360" poster="https://tails.boum.org/install/inc/videos/boot-menu-key.png">
- <source src="https://tails.boum.org/install/inc/videos/boot-menu-key.webm" type="video/webm">
+ <source src="https://tails.boum.org/install/inc/videos/boot-menu-key.webm" type="video/webm"/> 
 </video>
 </body>
```

**Comment by sajolida** [comment]
Hi @eighthave!

I'm not sure to understand your question: as I've written above, closing the `source` tag with " />" works around this easily but I don't think that it should be required.

**Comment by mquinson** [comment]
Hello @sajolida,
Could you please elaborate on what po4a is supposed to do? I understand that it shouldn't break on this file, but what should be translated? It seems to me that there is no content to be translated, right? 
I need this info because tags that do not need to be translated are not handled in the same way internally.
Thanks for the report and for the additional info,

**Comment by mquinson** [comment]
Hello, I think I now understand the problem. po4a expects its input to be valid [XHTML](https://www.w3schools.com/html/html_xhtml.asp) documents: Internally, it is based on an XML parser so this is not something you can change without a complete reimplementation of this module. That should not be impossible to do, but it's not very high on my list.
 
I plan to leave this issue open until after I improve the documentation and error messages to clearly state that valid HTML documents are not necessarily valid XHTML documents, the only ones that po4a can currently deal with.

If someone is willing to implement a pure HTML module, I'm willing to help. The first step would be to come up with a parser written in Perl that is not too intricated. For example for the YAML module, I was greatly inspired from the YAML::Tiny parser, even if I eventually rewrote many parts.

**Comment by sajolida** [comment]
Hi @mquinson,

In my exemple, there's nothing to translate in the <source> tag and I only expect po4a not to break (though I haven't checked what other attributes exists for <source>).

Given how your description of the underlying problem and that there's an easy workaround, I think that you're right to put this issue as super low priority or and could even discard it :)

**Comment by mquinson** [comment]
In the meanwhile, I may have found an idea to hack something together. I'm just stuck with something right now. Stay tuned ;)
