### ISSUE TITLE
Couldn't determine the input document's charset.

### ISSUE THREAD

**Issue by niklasolai** [mquinson/po4a#181]
I get this error and have no idea how to get it to work without removing my nordic characters. 

`po4a: Couldn't determine the input document's charset. Please specify it on the command line. (non-ASCII char at file.tex:45)
`
The command was `po4a-gettextize -f latex -m file.tex -p xx.po`

**Comment by jnavila** [comment]
Add a `-M` option. If using utf-8: `-M UTF-8`
