### ISSUE TITLE
support "YAML Front Matter" in Markdown documents

### ISSUE THREAD

**Issue by eighthave** [mquinson/po4a#196]
Many static site generators like Jekyll and Hugo use Markdown as the preferred format, with an extra bit of metadata at the top of the document known as "YAML Front Matter".  It is literally just a a piece of YAML stuck at the top of a Markdown document.  It is easy to detect, since the document will start with`/^\s*---\n/`.  It is easy to parse, since it is plain YAML.  Here's an example of parsing it in Python:
```python
import re
import yaml

with open("myfile.md") as fp:
    m = re.match(r'^\s*---\n(.+\n)---\n', fp.read(), flags=re.DOTALL)
    data = yaml.load(m.group(1))

```

I think po4a should parse it out, parse it to YAML, then include the key in the `#. ` string, and the value as the `msgid`.  For example, this Markdown:

```markdown
---
layout: page
title: All About Descriptions, Graphics, and Screenshots

---

Each app can have complete app store content, including localized descriptions,
feature graphics, and screenshots. 

```

Would be parsed into this .po:

```po
#. type: YAML Front Matter (layout)
msgid "page"
msgstr ""

#. type: YAML Front Matter (title)
msgid "All About Descriptions, Graphics, and Screenshots"
msgstr ""

#. type: Plain text
msgid "Each app can have complete app store content, including localized descriptions, feature graphics, and screenshots."
msgstr ""
```

Here are some docs on the format:
* https://jekyllrb.com/docs/front-matter/
* https://gohugo.io/content-management/front-matter/

And here are many files in this format:
* https://gitlab.com/fdroid/fdroid-website/-/tree/master/_docs

And here are many test cases for a Ruby parser of this format:
* https://github.com/jonschlinkert/gray-matter/blob/master/test/matter.js

@jonassmedegaard any way I can interest you in this one?  I'm happy to test again :-)

**Comment by eighthave** [comment]
It seems there is already a Perl library to do this: https://metacpan.org/pod/Text::FrontMatter::YAML

**Comment by eighthave** [comment]
I'm writing test cases for this now

**Comment by eighthave** [comment]
I started hacking on this, but didn't get very far.  Perl is very different than the languages I know, so I was hampered by that more than I thought.  The full patch including complete test files are attached here:  [0001-WIP-support-YAML-Front-Matter-in-Markdown-documents.patch.zip](https://github.com/mquinson/po4a/files/4372093/0001-WIP-support-YAML-Front-Matter-in-Markdown-documents.patch.zip)


This is the code that I wrote so far:
```diff
diff --git a/lib/Locale/Po4a/Text.pm b/lib/Locale/Po4a/Text.pm
index acdece13..7d929547 100644
--- a/lib/Locale/Po4a/Text.pm
+++ b/lib/Locale/Po4a/Text.pm
@@ -57,6 +57,7 @@ use vars qw(@ISA @EXPORT);
 
 use Locale::Po4a::TransTractor;
 use Locale::Po4a::Common;
+use YAML::Tiny;
 
 =head1 OPTIONS ACCEPTED BY THIS MODULE
 
@@ -514,16 +515,61 @@ sub parse_markdown_bibliographic_information {
     }
 }
 
+# Support YAML Front Matter in Markdown documents
+#
+# If the text starts with a YAML ---\n separator, the full text until
+# the next YAML ---\n separator is considered YAML metadata.
+#
+# If the information spans multiple lines, the following
+# lines must be indented with space.
+# If information is omitted, it's just a percent sign
+# and a blank line.
+#
+sub parse_markdown_yaml_front_matter {
+    my ($self,$line,$ref) = @_;
+    my ($nextline, $nextref);
+    my $yfm;
+    ($nextline, $nextref) = $self->shiftline();
+    while ($nextline =~ /^(?!---\n)$/) {
+       $yfm .= $1."\n";
+       $self->pushline($line."\n");
+       ($nextline, $nextref) = $self->shiftline();
+    }
+    my $yaml = YAML::Tiny->read_string($yfm)->[0]
+       || die "Couldn't read YAML Front Matter:\n $yfm\n $!";
+    my $wrapped_mode = 0;
+    while ((my $key, my $value) = each (%$yaml)) {
+       my $type = "YAML Front Matter ($key)";
+       my $paragraph = "";
+       if ($type eq 'ARRAY' or $type eq 'HASH') {
+           my $paragraph =  Dump($value);
+           $paragraph =~ s/---\n//;
+       } else {
+           $paragraph = $value;
+           print("$key: $value\n");
+       }
+        my $t = $self->translate($paragraph,
+                                 $ref,
+                                 $type,
+                                 "wrap" => 0);
+       do_paragraph($self,$paragraph,$wrapped_mode,$type);
+    }
+    return;
+}
+
 sub parse_markdown {
     my ($self,$line,$ref,$paragraph,$wrapped_mode,$expect_header,$end_of_paragraph) = @_;
     if ($expect_header) {
-        # Either we find and parse the bibliographic information,
-        # or there is no line with a percent sign.
+        # It is only possible to find and parse the bibliographic
+        # information or the YAML Front Matter from the first line.
         # Anyway, stop expecting header information for the next run.
         $expect_header = 0;
         if ($line =~ /^%(.*)$/) {
             parse_markdown_bibliographic_information($self, $line, $ref);
             return ($paragraph,$wrapped_mode,$expect_header,$end_of_paragraph);
+        } elsif ($line =~ /^---\n$/) {
+            parse_markdown_yaml_front_matter($self, $line, $ref);
+            return ($paragraph,$wrapped_mode,$expect_header,$end_of_paragraph);
         }
     }
     if (($line =~ m/^(={4,}|-{4,})$/) and
```

**Comment by mquinson** [comment]
This looks very good. Let me have a closer look.

**Comment by mquinson** [comment]
One thing that bother me is that in your test, you have the same msgid for both something coming out of the header and section title in your document. 
```
#. type: YAML Front Matter (title)
#: t-20-text/PandocYamlFrontMatter.md:7
msgid "YAML: does it fit in Markdown?"
msgstr ""

[...]

#. type: Title -
#: t-20-text/PandocYamlFrontMatter.md:10
#, no-wrap
msgid "YAML: does it fit in Markdown?"
msgstr ""
```

These entries only differ by their type, and I'm worried that it may disturb some tools out there (starting with po4a itself). I realize that the tests of the text module only contain some normalization, ie the parsing of a master document. It'd be better to also test the result of a translation. That would ensure that my above concerns are not sound. 

But this is not related to this issue. If you confirm that it works for you, that the produced translations are suitable for your needs, I'll merge your pull request in. Please don't forget to add a word in the NEWS file to document your change. If you do forget, I'll do it myself, no worry ;)

We should then work to improve the tests, in another issue.

Thanks for your interest,
Mt.

**Comment by eighthave** [comment]
That code is far from working, that's just as far as I got.  I don't understand Perl data structures, and also the po4a internal API.  I could even figure out how to get debug print working when running the tests.  I'm a Python/Java person.  If anyone has time to try to fill in the code in my patch, I'll happily test and tweak it.  I think I can do that much in Perl.

I'm fine with changing the test case to avoid known limitations, e.g. the same string in two places.

**Comment by eighthave** [comment]
@relan I see you do perl, any chance you could take a stab at this?  It would make f-droid.org require much less time to maintain.

**Comment by relan** [comment]
@eighthave, I'll have a look, though my Perl knowledge is quite limited and dates back to early 2000s.

**Comment by mquinson** [comment]
I'm having a look right now. If you want to discuss, please come to #po4a on IRC on oftc.

**Comment by mquinson** [comment]
Ok, I just pushed an attempt at fixing this issue. Please reopen with details if the problem persists.
