### ISSUE TITLE
 asciidoc: wrong unindented warning for hyphen lists

### ISSUE THREAD

**Issue by Jibec** [mquinson/po4a#211]
when converting this asciidoc content to pot:
```
- item
- item
-- item level 2
--item level 2
- item
```

I get this warning:

```
./index.adoc:4: It seems that you are adding unindented content to an item.
The standard allows this, but you may still want to change your document
to use indented text to provide better visual clues to writers.
```
I get this pot:
```
# SOME DESCRIPTIVE TITLE
# Copyright (C) YEAR Free Software Foundation, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2020-04-19 15:10+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#. type: Plain text
#: ./index.adoc:2 ./index.adoc:3 ./index.adoc:5
msgid "item"
msgstr ""

#. type: Plain text
#: ./index.adoc:5
msgid "item level 2 --item level 2"
msgstr ""
```
and the generated adoc is:

```
- item
- item
-- item level 2 --item level 2
- item
```

Here, there should be no warning.
It doesn't respect Asciidoc specification at all because hyphen lists only have one level: https://asciidoctor.org/docs/user-manual/#unordered-lists

**Comment by jnavila** [comment]
I don't understand the core of your issue: as you wrote, hyphen list don't have nested levels (with double hyphens). So writing:

```
-- item level 2
--item level 2
```
are not items level 2. Please also note that your hyphens are two different characters: on first line they are "minus" signs, whereas on second they are em dash. So even asciidoctor does not handle them the same. What's your expected po output on that?

**Comment by Jibec** [comment]
I feel like po4a consider lignes starting with "--" as lists items.

Also, po4a warns us about line 4, while both lines three and four should trigger an indentation error.

**Comment by jnavila** [comment]
Asciidoctor explicitly states:
```
You should reserve the hyphen for lists that only have a single level because the hyphen marker (-) doesn’t work for nested lists. Now that we’ve mentioned nested lists, let’s go to the next section and learn how to create lists with multiple levels.

```

**Comment by Jibec** [comment]
Well, indeed, ascidoc limits hyphen to a single level.
po4a should warn for both lines 3 and 4 because of missing indent.

**Comment by mquinson** [comment]
According to [the source code](https://github.com/mquinson/po4a/blob/master/lib/Locale/Po4a/AsciiDoc.pm#L380), po4a believes that lines starting with '--' are List Item Continuation or List Block.

**Comment by jnavila** [comment]
> According to [the source code](https://github.com/mquinson/po4a/blob/master/lib/Locale/Po4a/AsciiDoc.pm#L380), po4a believes that lines starting with '--' are List Item Continuation or List Block.

I don't think so, because the line you're referring to cannot match: it expects "--" alone on a line, not followed by stuff.

**Comment by jnavila** [comment]
> Well, indeed, ascidoc limits hyphen to a single level.
> po4a should warn for both lines 3 and 4 because of missing indent.

This is difficult, because once the offset has been reset by the first line, the second one is indented "correctly" WRT to it.

**Comment by jnavila** [comment]
Please note that we don't want to implement a asciidoc lint tool. Isn't the first warning explicit enough to trigger a check for the writer?

**Comment by Jibec** [comment]
Well, I'm confused about this issue. If we can't find an agreement on what is to be done, I'm fine with closing this. It's not a major issue.
--
Jean-Baptiste

**Comment by mquinson** [comment]
Is there any linter for asciidoc? That'd be really helpful here.

We could say that po4a must accept any input recognized as correct by this (hypothetical) tool, and *should* warn about errors when possible.

**Comment by ciampix** [comment]
Well there is a very recent standardization effort going on at the Eclipse foundation: https://projects.eclipse.org/proposals/asciidoc-language
hopefully that will bring a validation tool soon, but first step is drafting the proposal at the very least...

**Comment by mquinson** [comment]
Hello guys. I notice that @Jibec said that this bug can be closed if we fail to find an agreement on what should be done. I'm closing the bug now, but if anyone got an idea about it since 2020, please do not hesitate to reopen.

**Comment by Jibec** [comment]
thank you ♡
--
Jean-Baptiste
