### ISSUE TITLE
asciidoc: missing content when markup line of header isn't the same length as header itself

### ISSUE THREAD

**Issue by Jibec** [mquinson/po4a#212]
when converting this asciidoc content to pot:
```
My title
~~~~~~~

My paragraph

. *bold* text
badly intendation
. *bold* text
badly intendation
. *bold* text
badly intendation
```

I get this pot:
```
# SOME DESCRIPTIVE TITLE
# Copyright (C) YEAR Free Software Foundation, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2020-04-19 16:20+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#. type: Plain text
#: ./index.adoc:2
msgid "My title"
msgstr ""
```
and the generated adoc is:

```
My title
~~~~~~~

My paragraph

. *bold* text
badly intendation
. *bold* text
badly intendation
. *bold* text
badly intendation
```

Issues are:
* missing content in pot
* no warning on indentation

I can't find the right place in the asciidoc documentation, but the tilds line can be the length of previous line +/- 1

**Comment by jnavila** [comment]
The filter for asciidoc is quite clunky in po4a, so it's safer to adapt the document style to what po4a can handle.

Anyway, this type of title is now deprecated. 

> = Title

Should be used for DocTitle. See https://asciidoctor.org/docs/asciidoc-writers-guide/#titles-titles-titles

**Comment by Jibec** [comment]
I can't do that as what I do is an automation of fedora documentation system.
It contains about 1004 adoc files spitted in 70 Antora modules, 93 k strings | 1.8 M words.

I need po4a to either support this way of writting an heading, or to trigger a warning/error.

**Comment by mquinson** [comment]
I'm still wondering about what's going wrong here, but I agree that po4a should accept any valid input, unless this turns out to be *really* complex. This is true for the asciidoc format as with the other ones.

**Comment by Jibec** [comment]
I feel like line 400 handles two lines titles
because line 417: we can find one line titles


line 391 says: $line =~ m/^(={2,}|-{2,}|~{2,}|\^{2,}|\+{2,})$/

I feel like it's there:
https://github.com/mquinson/po4a/blob/master/lib/Locale/Po4a/AsciiDoc.pm#L397

could this "length($line)" be the source of the error?

**Comment by mquinson** [comment]
One way to know is to try changing it :) You could add `print STDERR "some string\n";` to get additional data.

Please come to the #po4a IRC channel of oftc to chat if you want. I want to finish my  lifting on the doc before I look at it myself.

**Comment by jnavila** [comment]
There are several arguments against using "Setext" style titles, as described [here](https://asciidoctor.org/docs/asciidoc-recommended-practices/#section-titles):

First it seems that the length of the underline *must* match the length of the title.
This is clearly not easy to deal with for writers.

 when translating, it is difficult, because you have to modify the line so that it matches the lenght of the translated content. It can get even worse with double width characters such as CJK or Russian, where I'm almost sure the behavior of Asciidoctor is not defined.

**Comment by mquinson** [comment]
@Jibec what is the specification here? How many '~' can be used to mark a title? I agree with you that this `length()` is probably the cause of the problem, but I don't know how to fix it.

**Comment by Jibec** [comment]
The real issue is that only some of the content is displayed in the po 
file.

I prefer to have no support of this old style header and have all the 
content available for translation.

**Comment by jnavila** [comment]
> The real issue is that only some of the content is displayed in the po file.

Can you post a sample of such occurence?

**Comment by Jibec** [comment]
The first message already contains the pot that I get with po4a, do you 
expect something else?

**Comment by jnavila** [comment]
Oh, sorry.

**Comment by jnavila** [comment]
http://asciidoc.org/userguide.html#X17 :

> A two line title consists of a title line, starting hard against the left margin, and an underline. Section underlines consist a repeated character pairs spanning the width of the preceding title *(give or take up to two characters)*

emphasis is mine. So some tolerances should be added...

**Comment by jnavila** [comment]
_character pairs_ ??? really ???

**Comment by Jibec** [comment]
thank you!
