### ISSUE TITLE
skipped YAML Front Matter items convert ints into strings

### ISSUE THREAD

**Issue by eighthave** [mquinson/po4a#217]
I'm in the process of converting https://letsencrypt.org/ to use _po4a_ and Weblate https://github.com/letsencrypt/website/issues/922 and I have the whole thing working, but in the process, I noticed that the YAML Front Matter has put quotes around ints, convering the data type in YAML from int to string.  This will likely break things like Hugo and Jekyll that is using YAML Front Matter.  Here's a quick example with `top_graphic` and `weight`:

__
```diff
@@ -1,28 +1,41 @@
 ---
-title: Über Let's Encrypt
-linkTitle: Let's Encrypt
-slug: about
-top_graphic: 1
 lastmod: 2019-11-11
+linkTitle: "Let's Encrypt"
 menu:
   main:
-    weight: 10
     parent: about
+    weight: '10'
+slug: about
+title: "Über Let's Encrypt"
+top_graphic: '1'
 ---

```

You can try this out by running `./gettextize` in my fork: https://gitlab.com/eighthave/letsencrypt-website

**Comment by mquinson** [comment]
I didn't test on your fork, though. Only locally. Feel free to reopen on need.

**Comment by eighthave** [comment]
works!  the latest commits fixed it
