### ISSUE TITLE
[doc] po4a(7) man page: possibly incorrect line

### ISSUE THREAD

**Issue by Fat-Zer** [mquinson/po4a#22]
doc/po4a.7.pod:508 says:
> If you prefer to kill the first translation instead when the second one was actually better, remove the second one from where it is and put the first one in the place of the second one.

Isn't here a mistake and it should be something like:
> If you prefer to kill the first translation instead when the second one was actually better, remove the second one from where it is and replace the first one with it.

Or just:
> If you prefer to kill the first translation instead when the second one was actually better, replace the the first one with the second.

It shouldn't be necessary to remove the second again as far as they are exactly the same

**Comment by mquinson** [comment]
I agree. Your understanding is good here. Could you please do the change?

Thanks for being so careful.

**Comment by Fat-Zer** [comment]
Also next line sounds wierd (not sure what was meant there):

doc/po4a.7.pod:760
> It is also possible to customize a module or new / derivative / modified modules by putting a module in F<lib/Locale/Po4a/>, and adding F<lib> to the paths specified by the PERLLIB or PERL5LIB environment.

**Comment by Fat-Zer** [comment]
The last section «Educating developers about translation» refers to SGML a lot, I suppose it should be replace by a more generic term, e.g. «documentation», because it supposed to be a general section, isn't it?

doc/po4a.7.pod:1076
>In the po4a project, translated documents are not source files anymore. Since
SGML files are habitually source files, it's an easy mistake. That's why all
files present this header:

doc/po4a.7.pod:1183
>One of my dreams would be to integrate somehow po4a to Gtranslator or
Lokalize. When an SGML file is opened, the strings are automatically extracted.
When it's saved a translated SGML file can be written to disk. If we manage
to do an MS Word (TM) module (or at least RTF) professional translators may
even use it.

**Comment by Fat-Zer** [comment]
yet another typo:
doc/po4a.7.pod:751
>once before editing the PO file**s** to update them and once afterward to get a
completely updated translated document.

PS: I may fix those a bit later if you nevermind...

**Comment by mquinson** [comment]
Please open one bug per issue, it is much easier to sort it out. I may need a few days before I can work on po4a again, so please feed me we nice bug reports and pull requests ;)
