### ISSUE TITLE
po4a chokes on images + text in tables

### ISSUE THREAD

**Issue by ciampix** [mquinson/po4a#226]
This PR is taken from here: https://gitlab.com/kicad/services/kicad-doc/-/issues/697
Po4a has issues when processing tables. The following minimal example shows the issue:
```
|====
|First col
|Second col

image::foo.png[alt="Alt"]

Text below image 1
|====

image::foo.png[alt="Alt"]

Text below image 2
```

After processing with po4a, e.g. po4a-normalize -f asciidoc test.adoc, this ends up as:
```
|====
|First col
|Second col

image::foo.png[alt="Alt"]
  Text below image 1
|====

image::foo.png[alt="Alt"]

Text below image 2
```
i.e. "Text below image 1" becomes "verbatim" text in asciidoc.
This has the strange side effect of creating a " in docbook, which is converted to a "/fvlisting" (fancyverb) in latex. Xelatex processes this using a temporary file, and chokes reading it back (/VerbatimInput) when it contains UTF-8 multibyte sequences starting with e.g. <0xC4> or <0xC5> (<0xC3> is fine).

This is an issue e.g. for Polish

Version affected are from v0.55 to current master (0.58+)

**Comment by jnavila** [comment]
Ah, it seems to be related to the changes I added to perform cell by cell segmentation.

BTW, is this correct asciidoc? IIRC, unless specified with column or cell attributes, cell content are verbatim. Moreover, complex content in tables is frowned upon.

Anyway, I'll add your case to the tests and try to fix it.

**Comment by mquinson** [comment]
I have a fix for it, but it breaks elsewhere :(

[patch.txt](https://github.com/mquinson/po4a/files/4603560/patch.txt)

This breaks this test:
```
    # | --- fmt/asciidoc/TablesCells.norm       2020-04-28 12:18:22.088361295 +0200
    # | +++ tmp/fmt/asciidoc/TablesCells.norm   2020-05-09 15:58:57.631580591 +0200
    # | @@ -86,7 +86,8 @@
    # |  .^|Prefix the `{vbar}` with a `.` and `{caret}` to center the content in the cell vertically
    # |  .<|Prefix the `{vbar}` with a `.` and `<` to align the content to the top of the cell
    # |  .>|Prefix the `{vbar}` with a `.` and `>` to align the content to the bottom of the cell
    # | -  3+^.^|This content spans three columns (`3{plus}`) and is centered
    # | +
    # | +3+^.^|This content spans three columns (`3{plus}`) and is centered
    # |  horizontally (`{caret}`) and vertically (`.{caret}`) within the cell.
    # |  
    # |  |===
    # | @@ -104,7 +105,8 @@
    # |  e|This content is emphasized.
    # |  
    # |  .^l|This content is aligned to the top of the cell and literal.
    # | -  v|This cell contains a verse that may one day expound on the wonders of
    # | +
    # | +v|This cell contains a verse that may one day expound on the wonders of
    # |  tables in an epic sonnet.
    # |  
    # |  |===
```

**Comment by mquinson** [comment]
In general, I find it very difficult to maintain both the cell segmentation and the default mode. I would advise that we drop the default mode and make the cell segmentation the only possibility here. That would help simplifying the source code, even if this means to invalidate many existing translations.

At the very least, we should change the default to the cell segmentation mode now, and kill the other mode in the future.

What do you think?

**Comment by jnavila** [comment]
Being the proponent of table cell segmentation, I'm not against it.  For Kicad's doc which relies on full table segmentation so @ciampix 's  thoughts and maybe for Fedora's @bexelbie 's thoughts on this would be welcome.

**Comment by ciampix** [comment]
You devs rock! Thanks!

**Comment by jnavila** [comment]
@ciampix If you have the opportunity to test the "tablecells" option, please give it a chance!
