### ISSUE TITLE
Documentation for -o (extra options)

### ISSUE THREAD

**Issue by nickoe** [mquinson/po4a#233]
Reading the manpage for po4a-translate for example shows this description for the -o option.

> Extra option(s) to pass to the format plugin. Specify each option in the 'name=value' format. See the documentation of each plugin for more information about the valid options and their meanings.

I use asciidoc and the options are listed in https://po4a.org/man/man3/Locale::Po4a::AsciiDoc.3pm.php

An example option would be `-o tablecells`, but this does  not look like a name value format.

**Comment by mquinson** [comment]
Indeed, options can be either 'name=value' or 'name' alone, depending on the option. For example,  you could pass '-o tablecells' to the AsciiDoc parser, while the text parser would accept '-o tabs=split'.

All occurrences of this documentation element should be fixed: po4a, po4a-translate, po4a-updatepo, etc. In the po4a-* scripts, it should be added that the exact same options should be passed to the parsers for both updatepo and translate.

Thanks for reporting (and asking the questions on IRC :)
