### ISSUE TITLE
 [doc] po4a(7) man page: a line sounds wierd

### ISSUE THREAD

**Issue by Fat-Zer** [mquinson/po4a#26]
Also next line sounds wierd (not sure what exactly was meant there):

doc/po4a.7.pod:760
> It is also possible to customize a module or new / derivative / modified modules by putting a module in F<lib/Locale/Po4a/>, and adding F<lib> to the paths specified by the PERLLIB or PERL5LIB environment.

Reported on #22 before.

**Comment by mquinson** [comment]
If you write your own module, or edit and customize an existing module, you can make it visible to the po4a scripts by copying your file into a path called </bli/blah/blu/lib/Locale/Po4a/> and then adding the path </bli/blah/blu> in the PERLIB or PERL5LIB environment variable.

Not perfect either (so feel free to edit), but hopefully easier to understand.
