### ISSUE TITLE
po4a-translate not working anymore

### ISSUE THREAD

**Issue by elchevive** [mquinson/po4a#265]
Hi,

I got a openSUSE bug about po4a-translate not working anymore on wxmaxima packages (https://bugzilla.opensuse.org/show_bug.cgi?id=1175977)

In short, po4a version 0.52 on Leap 15.1 and 15.2 works:
https://build.opensuse.org/package/live_build_log/Education/wxMaxima/openSUSE_Leap_15.2/x86_64

While po4a version 0.61 on Tumbleweed don't:
https://build.opensuse.org/package/live_build_log/Education/wxMaxima/openSUSE_Tumbleweed/x86_64

```
cd /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.07.0/build/info && /usr/bin/po4a-translate -k 0 -f text -o markdown -m /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.07.0/info/wxmaxima.md -p /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.07.0/locales/manual/pl.po -l wxmaxima.pl.md -M UTF-8
[  163s] Unknown format type: text.
[  163s] List of valid formats:
[  163s]   - asciidoc: AsciiDoc format.
[  163s]   - dia: uncompressed Dia diagrams.
[  163s]   - docbook: DocBook XML.
[  163s]   - guide: Gentoo Linux's XML documentation format.
[  163s]   - ini: INI format.
[  163s]   - kernelhelp: Help messages of each kernel compilation option.
[  163s]   - latex: LaTeX format.
[  163s]   - man: Good old manual page format.
[  163s]   - pod: Perl Online Documentation format.
[  163s]   - rubydoc: Ruby Documentation (RD) format.
[  163s]   - sgml: either DebianDoc or DocBook DTD.
[  163s]   - texinfo: The info page format.
[  163s]   - tex: generic TeX documents (see also latex).
[  163s]   - text: simple text document.
[  163s]   - wml: WML documents.
[  163s]   - xhtml: XHTML documents.
[  163s]   - xml: generic XML documents (see also docbook).
[  163s]   - yaml: YAML documents.
```
The command seems fine but between 0.52 and 0.61 po4a-translate doesn't understand the '-f text' anymore.

I compiled 0.61 in Leap 15.2 to test and it gives me the same error. 

Regards

**Comment by mquinson** [comment]
Hello,

I think I need access to the input file provided to po4a, because `po4a-translate -f text` works in the tests:
https://travis-ci.org/github/mquinson/po4a/jobs/716879397#L5316

Could you tell me where I could find those files? Unfortunately, I don't have access to a Suse box myself, so I'll need to retrieve them manually. A git would be perfect.

Thanks for the report,

**Comment by mquinson** [comment]
I note that the original bug reporter suspects that the problem is linked to the libexec transition. I have no idea of what it is, but it'd be interesting to test the po4a programs before packaging. Please refer to https://github.com/mquinson/po4a/blob/master/CONTRIBUTING.md#testing-your-changes to see how to do that.

In particular, I'd be interested in the result of the following command:
```
PERL5LIB=/path/to/po4a/source/tree/lib/ perl $PERL5LIB../po4a-translate -k 0 -f text -o markdown -m /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.07.0/info/wxmaxima.md -p /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.07.0/locales/manual/pl.po -l wxmaxima.pl.md -M UTF-8
```

**Comment by elchevive** [comment]
Hi,

Sure, its wxmaxima source code, you can find it here (20.07 version - 15Mb):

https://github.com/wxMaxima-developers/wxmaxima/releases

or download just 2 files from here (the .md and a .po - 35kb):  https://we.tl/t-gA5T3yZjfu

This libexec change has nothing to do with this (is just a coincidence as Leap versions doesn't have this libexec change and also had this problem).

I made the following test:
1. uninstall the compiled rpm
2. download 0.61 source cide and extracted it
3. run one test with -f text (the error occurs), and test the same with another type:

```
linux-qz7m:/home/elchevive/Downloads/po4a-0.61/lib # zypper rm po4a
Reading packages...

The following 2 packages will be REMOVED:
  po4a po4a-lang

Continue? [y/n/v/...? display all options] (s): d    

The following 2 packages will be REMOVED:
  po4a       0.61-lp152.67.1  noarch  obs://build.opensuse.org/devel:languages:perl
  po4a-lang  0.61-lp152.67.1  noarch  obs://build.opensuse.org/devel:languages:perl

Continue? [y/n/v/...? display all options] (y): s
(1/2) Removing po4a-0.61-lp152.67.1.noarch .................................[done]
(2/2) Removingpo4a-lang-0.61-lp152.67.1.noarch ............................[done]
 
linux-qz7m:/home/elchevive/Downloads/po4a-0.61/lib # exit
exit
elchevive@linux-qz7m:~/Downloads/po4a-0.61/lib> PERL5LIB=../lib/ perl ../po4a-normalize -f text -o markdown t-20-text/PandocYamlFrontMatter.md
Unknown format type: text.
List of valid formats:
  - asciidoc: AsciiDoc format.
  - dia: uncompressed Dia diagrams.
  - docbook: DocBook XML.
  - guide: Gentoo Linux's XML documentation format.
  - ini: INI format.
  - kernelhelp: Help messages of each kernel compilation option.
  - latex: LaTeX format.
  - man: Good old manual page format.
  - pod: Perl Online Documentation format.
  - rubydoc: Ruby Documentation (RD) format.
  - sgml: either DebianDoc or DocBook DTD.
  - texinfo: The info page format.
  - tex: generic TeX documents (see also latex).
  - text: simple text document.
  - wml: WML documents.
  - xhtml: XHTML documents.
  - xml: generic XML documents (see also docbook).
  - yaml: YAML documents.
elchevive@linux-qz7m:~/Downloads/po4a-0.61/lib> PERL5LIB=../lib/ perl ../po4a-normalize -f ini -o markdown t-20-text/PandocYamlFrontMatter.md
File t-20-text/PandocYamlFrontMatter.md does not exist.
elchevive@linux-qz7m:~/Downloads/po4a-0.61/lib>
```

**Comment by mquinson** [comment]
Thanks for the new informations. I'm really surprised of what you're seeing. Markdown is definitely working here, that's really weird. I'll need to find some time to explore the issue by myself but this won't happen this week.

Until then, could you please tell me what happens if you add `--verbose` on the command lines? po4a needs it to report the errors observed when loading a format backend.

**Comment by mquinson** [comment]
FYI, the error message will now be displayed even if you don't pass --verbose to ease the life of users.

Thanks for reporting.
