### ISSUE TITLE
xreflabel not translated

### ISSUE THREAD

**Issue by roptat** [mquinson/po4a#267]
Hi!

I'm having some issues with an xreflabel in a docbook document that is not translated by po4a. The string is the same as the title of the section and is present in the po file (the title is translated). I have other files with xreflabels that are translated though, so I wonder why this file is not. Example:

In

```
<sect1 id="ch-tools-generalinstructions" xreflabel="General Compilation Instructions">
  <title>General Compilation Instructions</title>
```

Only the title is translated:

```
<sect1 id="ch-tools-generalinstructions" xreflabel="General Compilation Instructions">
  <title>Instructions générales de compilation</title>
```

However,

```
<sect1 id="ch-config-shells" xreflabel="Creating the /etc/shells File">
  <title>Creating the /etc/shells File</title>
```

is properly translated:

```
<sect1 id="ch-config-shells" xreflabel="Créaction du fichier /etc/shells">
  <title>Créaction du fichier /etc/shells</title>
```

I get this behavior with po4a 0.55, 0.57 and 0.61.

**Comment by roptat** [comment]
ah nevermind, the xreflabel is never translated, it's only translated as postprocessing on my end. So the issue should be that xreflabel is not translated.

**Comment by mquinson** [comment]
You can modify the default behavior for a given tag or attribute: https://po4a.org/man/man3/Locale%3A%3APo4a%3A%3ADocbook.3pm.php.en#lbAC and look for 'attributes' in https://po4a.org/man/man3/Locale::Po4a::Xml.3pm.php

I guess that  adding `-o attributes="xreflabel"` to your command line or to the options in po4a.conf will do what you want.

But I have an extra question: are you sure that it's a good idea to translate those strings? Are they visible to the user? If so, when/how? If the strings are not visible, it's better to not translate them. It reduces the risk of breaking the formatting...

**Comment by roptat** [comment]
Ah! Thanks for the answer, I think that's exactly what I need. As the name suggests, xreflabel is the label for an xref, meaning it's the text shown to readers when there's a link to that chapter or section.

**Comment by mquinson** [comment]
Ok, thanks for the additional info on xreflabel. Is there any situation where this attribute should not be translated? If not, I'm considering integrating this patch to the default definition in po4a:

```
diff --git a/lib/Locale/Po4a/Docbook.pm b/lib/Locale/Po4a/Docbook.pm
index b34daf86..ef8959e3 100644
--- a/lib/Locale/Po4a/Docbook.pm
+++ b/lib/Locale/Po4a/Docbook.pm
@@ -2045,6 +2045,9 @@ sub initialize {
     $self->{options}{'_default_translated'} .= " <year>";
     $self->{options}{'_default_inline'}     .= " <year>";

+    # xreflabel is the label to use when referencing an element that has no title
+    $self->{options}{'_default_attributes'} .= " xreflabel";
+
     # ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

     $self->{options}{'_default_attributes'} .= '
```

**Comment by roptat** [comment]
I'm thinking maybe the label is often the same as the title, but it wouldn't always make sense to translate it in the same way. At the same time, it always makes sense to translate it. Is there a way for po4a to generate two entries with different contexts in the po? If it's too complex, your patch already improves the situation.

**Comment by mquinson** [comment]
I think it's rather difficult to have contexts in the translations. If someone proves me wrong with a patch, that's perfect. But if this patch is enough to solve this issue, that's the way I'd like to go. My time is sparse right now :)

**Comment by roptat** [comment]
OK, I understand, thanks for your time! Your patch is already a great improvement. I'll see if I can make a patch for contexts. This is also an issue for another project that uses texinfo, so I'd like to solve this issue as well.

**Comment by mquinson** [comment]
thanks for reporting the issue and your feedback. I'm looking forward your patch ;)
