### ISSUE TITLE
[doc] po4a(7) man page: last section refers to SGML a lot

### ISSUE THREAD

**Issue by Fat-Zer** [mquinson/po4a#27]
The last section «Educating developers about translation» refers to SGML a lot, I suppose it should be replace by a more generic term, e.g. «documentation», because it supposed to be a general section, isn't it?

doc/po4a.7.pod:1076
>In the po4a project, translated documents are not source files anymore. Since
SGML files are habitually source files, it's an easy mistake. That's why all
files present this header:

doc/po4a.7.pod:1183
>One of my dreams would be to integrate somehow po4a to Gtranslator or
Lokalize. When an SGML file is opened, the strings are automatically extracted.
When it's saved a translated SGML file can be written to disk. If we manage
to do an MS Word (TM) module (or at least RTF) professional translators may
even use it.

Reported on #22 before.

**Comment by mquinson** [comment]
You are right, it should be improved. I will try to do it soon.

Thanks. Could we maybe close #22?
