### ISSUE TITLE
[doc] po4a(7) man page: one more typo

### ISSUE THREAD

**Issue by Fat-Zer** [mquinson/po4a#28]
one more typo:
doc/po4a.7.pod:751
>once before editing the PO file**s** to update them and once afterward to get a
completely updated translated document.

Reported on #22 before.

**Comment by mquinson** [comment]
I am playing with the idea of adding a --untypot parameter to the po4a script. This would help dealing with such situations in a better way. Until then, we'll have to fix it manually.
