### ISSUE TITLE
Build Failure due to Po4aBuilder resetting PERL5LIB.

### ISSUE THREAD

**Issue by deatondg** [mquinson/po4a#285]
On my system (Homebrew perl with custom PERL5LIB), `./Build` fails due to various include errors because my PERL5LIB variable has been reset. The issue is in Po4aBuilder.pm, and I have fixed the errors in a PR.

**Comment by mquinson** [comment]
Since #286 was merged, this issue should be closed. Feel free to reopen if I'm wrong.
