### ISSUE TITLE
po4a command in split mode failed to extract messages that belong to an yaml master file

### ISSUE THREAD

**Issue by PhuNH** [mquinson/po4a#289]
This is my config file _po4a.cfg_:
```
[po4a_paths] po/$master.pot $lang:po/$lang/$master.po
[type: text] content/_index.md $lang:content/$lang/_index.md master:file=messages opt:"-o markdown"
[type: yaml] i18n/en.yaml $lang:i18n/$lang.yaml master:file=messages-shared 
[options] -M utf-8 -L utf-8
```
I run it with `po4a po4a.cfg` command. The output is:
```
 (204 entries)
msggrep did not create '/tmp/po4aNSUH.pot'. Used command:
  msggrep -N "i18n/en.yaml" -o /tmp/po4aNSUH.pot /tmp/po4a-temp-pot-mYvh.pot
Please report that bug, along the information allowing to reproduce it.
```
I'm using v0.61 but as I can see the behavior in v0.62 is the same: for yaml files, message references are key names, not file names and line numbers. My guess is that since there's no information about source files, `msggrep` cannot do what is expected.

**Comment by mquinson** [comment]
Could you please provide the files that can be used to reproduce the bug? Either as attachment or gist, or as link to the existing project where you're experiencing the issue, or even better, as a pull request to PO4A to create a failing test reproducing the issue.

Thanks for reporting, and thanks for your help debugging it,

**Comment by PhuNH** [comment]
[po4a-split-yaml.zip](https://github.com/mquinson/po4a/files/5861151/po4a-split-yaml.zip) contains the minimal example I just created. There is nothing special here I think, just a minimal example is enough.
- At first I had 3 files: _po4a.cfg_, _content/\_index.md_, and _i18n/en.yaml_; the _po_ folder is empty;
- I created 2 POT files in _po_ folder using commands:
```
po4a-gettextize -f text -o markdown -m content/_index.md -M utf-8 -p po/messages.pot
po4a-gettextize -f yaml -m i18n/en.yaml -M utf-8 -p po/messages-shared.pot
```
- Then I copied those 2 POT files into _po/vi_, renamed them from .pot to .po, and translated them
- Finally, I ran `po4a po4a.cfg`, the error is
```
 (5 entries)
msggrep did not create '/tmp/po4aBXle.pot'. Used command:
  msggrep -N "i18n/en.yaml" -o /tmp/po4aBXle.pot /tmp/po4a-temp-pot-kt2y.pot
Please report that bug, along the information allowing to reproduce it.
```
Here is the [po4a-temp-pot-kt2y.pot](https://github.com/mquinson/po4a/files/5861175/po4a-temp-pot-kt2y.txt) file if you need (I changed it to .txt to be able to upload it).

**Comment by PhuNH** [comment]
The problem here is po4a in split mode uses `msggrep` to search the combined pot file for entries that correspond to each master doc, and it cannot find any entry for the YAML master doc because currently entries created from an YAML master doc do not have the usual reference of a file name and a line number but only names of YAML keys that lead to the value.
