### ISSUE TITLE
Po4a script fails on Windows

### ISSUE THREAD

**Issue by eevan78** [mquinson/po4a#293]
I have found a problem with po4a tool on Windows. It is mostly because calls of external tools (msgfmt, msginit, msggrep...) assume Linux, so they use /dev/null. There is another one that use setting of an environment variable directly before calling executable (not available on Windows). All that cause the script to fail on Windows.
Therefore, I made a quick and possibly dirty fix that worked on my system.
Maybe it could be done more elegantly than this...
Zipped patch is attached.
I'm willing to help testing and improving po4a on Windows!

[po4a.zip](https://github.com/mquinson/po4a/files/5975682/po4a.zip)

**Comment by mquinson** [comment]
Thanks a lot for these changes! Windows is so difficult for me that your help is really really welcome here. I'd love if you could help us with that. Please tell me how I could help you helping us.

**Comment by eevan78** [comment]
Hi Martin,
do you have any standard tests for various tools within po4a suite? That
would be helpful. If not, then I will start one by one and try them out
with various input on Windows. And let's see what problems arise. I'll try
my best to fix them.

уто, 16. феб 2021. 02:28 Martin Quinson <notifications@github.com> је
написао/ла:

**Comment by mquinson** [comment]
Hello,

we do have a test suite, with many tests. That's what you get when you do `./Build test`. I've no idea whether it works under Windows. I'd be somewhat surprised, but you'll have to test.

See also https://github.com/mquinson/po4a/blob/master/CONTRIBUTING.md#testing-your-changes

Thanks,
