### ISSUE TITLE
Connect po4a to a translation platform

### ISSUE THREAD

**Issue by Jibec** [mquinson/po4a#30]
Hi, I see some "zanata.xml" files about a project in "translate.zanata.org". But the content is out of date (last update is from september 2016).

I suggest to use this other translation platform: https://hosted.weblate.org

You'll ask Michal to create two component:
Bin: https://github.com/mquinson/po4a/tree/master/po/bin
 => is this core software? If so, I suggest to name this component "po4a"
Pod: https://github.com/mquinson/po4a/tree/master/po/pod
 => is is "Plain Old Documentation"? If so, I suggest to name this component "documentation"

you may connect a either the github git repo  or the alioth git repo.

**Comment by mquinson** [comment]
I would welcome a pull request adding the possibility to translate using weblate, as I won't have the time to do so myself anytime soon. 

Btw, why do you say that the zanata thing is out of date?

**Comment by Jibec** [comment]
I think it is out of date because the three component are locked and last update is "08/09/16 21:55 by emptty"
![capture du 2017-06-12 07-01-14](https://user-images.githubusercontent.com/474883/27019924-f6a7afba-4f3c-11e7-9650-c44dc27133b6.png)


The magic with Weblate is you don't have to change anything in you code (I'll make a commit to remove zanata.xml files, but I think that's it), you may just have to confirm to @nijel that this is ok for you. He may have a few question, but I assume not much as I was able to do it myself without a lot of knowledge (https://github.com/mquinson/po4a/pull/31).

Please also be explicit if you want weblate to use github repository or alioth's repository.

**Comment by mquinson** [comment]
Hello, sorry for the delay.

I herby confirm my interest to connect weblate to the po4a repository.
Please use the alioth repository for that. 

I would also like to keep the zanata files for a little while, if they
are not harming anything.


Many thanks for your help, and sorry again for the delay.
Mt.

-- 
Ce n’est pas la girouette qui tourne, c’est le vent. -- Edgar Faure

**Comment by Jibec** [comment]
@nijel : I assume this is the Alioth git address is https://alioth.debian.org/anonscm/git/po4a/po4a.git as show in https://alioth.debian.org/scm/browser.php?group_id=30267

Mask are:

* po/bin/*.po for "po4a" component
* po/doc/*.po for "po4a-doc" component

**Comment by nijel** [comment]
That's all I need, but next time please use hosting request form on Hosted Weblate for this.

The project has been imported to Hosted Weblate:

https://hosted.weblate.org/projects/po4a/

Please check that everything looks correct.

As you're hosting Git repository on not directly supported platform, you
will have to merge changes from Weblate manually. If you want Weblate to
automatically pull changes from your repository, please add notification
hook to your post receive git hook, see
https://hosted.weblate.org/data/po4a/

PS: Having better support for Alioth was planned, but in light of scheduled migration of Alioth to different platform, I've not spent any time on that.

The free hosting still costs us some money, so if you're in position to
do that, you are welcome to support us in providing this service for
free:

https://weblate.org/donate/

**Comment by Jibec** [comment]
oh dear, this was unexpected as it means more work. And indeed, there is a migration in discussion for Alioth' migration here: https://lists.debian.org/debian-devel/2017/05/msg00095.html

Martin, what do you prefer?

1. connect Weblate to GitHub, which will gives you automation for translations (pull&push) and as for any other code, manually sync Alioth/GitHub
2. connect Weblate to Alioth, you'll have to go do one more manual sync task

For a day-to-day usage (on github), Weblate's modifications will go to a new Pull Request, and until to merge it, Weblate will add every modification for every languages. So before pushing a new release, you'll just have to merge Weblate's commits.

**Comment by nijel** [comment]
As for Alioth, there is also survey ongoing about features wanted there, see https://lists.debian.org/debian-devel/2017/06/msg00233.html

**Comment by mquinson** [comment]
Hello,

given the context, I prefer if you can connect it to GitHub. I'll do
the updates manually.

Thanks for your time, 
Mt

**Comment by nijel** [comment]
Done, here is first PR: https://github.com/mquinson/po4a/pull/32

To notify Weblate about changes in your repository please add Weblate Service to your project:

https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

**Comment by mquinson** [comment]
Thanks. This is done. Please note that the procedure you pointed me to should be updated, as github decided that Services should not be with webhooks anymore in the settings. See this capture:

![capture du 2017-06-19 09-29-27](https://user-images.githubusercontent.com/624847/27274117-590db2f4-54d2-11e7-945a-160780a4b84a.png)
