### ISSUE TITLE
Make po4a a one-stop shop?

### ISSUE THREAD

**Issue by porridge** [mquinson/po4a#301]
I have a very simple [Python app](https://github.com/porridge/bambam) which consists of a single Python script. It also has a manpage. The manpage and the Python file share some translatable strings. I'd like to provide a single `pot` file to translators so that  identical messages are translated only once.

Currently I:
1. "manually" use `xgettext` to create one `pot` file for the Python script, and
2. use `po4a` to create another `pot` file for the man page.
3. Then I use `msgcat` to merge them into a single pot file for translators.

I wonder whether it is possible to have `po4a` also take care of the first `pot` file? If not, then please view this as a feature request. 😉 

Also, thank you for this awesome tool!

**Comment by mquinson** [comment]
Hello,

I must say that I'm not sure of how to implement it correctly. Each and every programming language has its own way of extracting the strings that should be translated, and it'd be difficult to unify in po4a. Also, I'm really not convinced that there will be a lot in common between the script messages and the documentation. From my experience, there is almost nothing between the bin/ and doc/ pot files in po4a. The documentation tend to be paragraph-oriented while scripts have much shorter messages. You may have one or two sentences in common, but not much I guess.

Another problem with this proposal is that the translations have a different lifetime. The ones collected through po4a are only useful when updating the translation of the documentation, while the ones to be fed to python must be installed on user's machines. It seems to me that merging them together would be a waste of resources for the users.

Thanks for your support and for reporting anyway,
Mt.

**Comment by porridge** [comment]
> I must say that I'm not sure of how to implement it correctly. Each and every programming language has its own way of extracting the strings that should be translated

In my mind the heavy lifting would be done by calling `xgettext`...

> Also, I'm really not convinced that there will be a lot in common between the script messages and the documentation. From my experience, there is almost nothing between the bin/ and doc/ pot files in po4a. The documentation tend to be paragraph-oriented while scripts have much shorter messages. You may have one or two sentences in common, but not much I guess.

Right. I admit my app is tiny. The command line options' descriptions make up the bulk of overlapping strings between the program code and the documentation (i.e. its man page).

> Another problem with this proposal is that the translations have a different lifetime. The ones collected through po4a are only useful when updating the translation of the documentation, while the ones to be fed to python must be installed on user's machines. It seems to me that merging them together would be a waste of resources for the users.

Right, I agree that for anything of substantial files this would be somewhat wasteful.

Thanks for taking the time to look at my report. I don't mind if you close it. :-)

**Comment by mquinson** [comment]
Thanks for your support.
