### ISSUE TITLE
po4a is memory hungry

### ISSUE THREAD

**Issue by jnavila** [mquinson/po4a#302]
When running po4a on [my project](https://github.com/jnavila/git-manpages-l10n), I observe two issues:

* Each processed language eats up around 400MB of memory.  This huge compare to size of po files which are around 4MB. It seems that each translated file is loaded in memory but not released when switching to the next file.
* No memory is released between the processing of two languages. I would expect a large portion of the memory to be given back, or at least reused between languages, but here, each language adds another 400MB of memory usage. With 21 languages to process, memory usage tops up to 8GB of memory, which can provoke swapping and freezing.

This behavior is unexpected, given that most of the processing should be in stream mode, with ephemeral memory allocation. IIUC, Perl uses reference counting for memory management, so memory is released as soon as no reference is pointing on it.  This seems to imply that po4a processing somehow keeps references on all allocated memory.

I bisected the issue to the commit 0b615f02a7eb5d8284834670ae6b77d39cd9c75e :

```
commit 0b615f02a7eb5d8284834670ae6b77d39cd9c75e
Author: Martin Quinson <martin.quinson@ens-rennes.fr>
Date:   Wed Apr 15 10:40:37 2020 +0200

    teach our tools about all flags added to po entries by gettext tools
```

**Comment by jnavila** [comment]
The commit found by bisect does not make sense...

**Comment by Fat-Zer** [comment]
I couldn't reproduce it with po4a-0.63.

To be specific, I've tried to clone your repository and run `make po4a.conf; po4a po4a.conf`. The memory usage of the po4a process didn't exceeded `50M` according to `htop`. It seems all the 

Could you elaborate a bit on how to reproduce it?

<hr>

System info: Gentoo Linux; amd64; perl-v5.30.3; po4a-0.63

**Comment by jnavila** [comment]
Hmm... I just tried again on another system (Ubuntu 16.04; perl-v5.22.1, po4a-0.62) and it does exhibit the same behaviour.

The system on which the issue appears is a Debian testing; perl-v5.32.1, po4a-0.63)

**Comment by jnavila** [comment]
Maybe a bug in Perl: https://github.com/Perl/perl5/issues/18604

**Comment by jnavila** [comment]
Strangely, reverting 0b615f02a7eb5d8284834670ae6b77d39cd9c75e limits the amount of used memory to  around 400MB in total, even if po4a keeps using more and more memory during the translation process.

**Comment by Fat-Zer** [comment]
If the perl leaks on each regex match as the bug suggests, than due to 0b615f0 it adds an extra match for each additional `known_flags` for each PO-entry (that has flags, which is every single one of them due to `priority` in your case). So that the known_flags increased ~15 times may drastically effect the amount of leakage because of it... To confirm it, you may try to replace the `\s`'s with spaces (` `) on the line 1480: https://github.com/mquinson/po4a/blob/0b615f02a7eb5d8284834670ae6b77d39cd9c75e/lib/Locale/Po4a/Po.pm#L1480

**Comment by jnavila** [comment]
changing the line to a straight substring search:

```perl
			if (index($flags, " $flag ") != -1) {     # if flag to be set
```
reduces the memory footprint to the low values you mentionned and even seems to accelerate the process.

**Comment by jnavila** [comment]
Please note that this issue  was not specific to asciidoc.
