### ISSUE TITLE
Asciidoc: Handling of comments

### ISSUE THREAD

**Issue by eevan78** [mquinson/po4a#307]
I'm translating Weechat documentation using po4a. Source files are in .adoc format and get processed with Asciidoctor to produce HTML.

Asciidoctor is using some tags in comments like this:

```
// tag::standard[]
   some multiline asciidoc text
// end::standard[]

// tag::debug[]
   some multiline asciidoc text
// end::debug[]
```

After po4a processing, these tags get into the comments of appropriate .po msgid strings, but discarded on generation to adoc.

Without these tags, Asciidoctor is producing errors.

Is there a way to simply pass the comments to the output, at the same position as where they appear in the original document?

**Comment by jnavila** [comment]
OH. I didn't know this feature of asciidoctor. This should be easy to add, but I'm not sure to have time soon. If you need it quickly and have basic knowledge of Perl, look at

https://github.com/mquinson/po4a/blob/a69b48eda3ebd66eec30a34a377c7a00c6f8e36c/lib/Locale/Po4a/AsciiDoc.pm#L616-L625

Where comments are processed.

**Comment by eevan78** [comment]
Thanks a lot for the tip, I'll give it a try!

**Comment by eevan78** [comment]
Here is a working solution in my case. Tested with 2 files from Weechat documentation that contain them. I'm not sure if it is good in general, because I don't know where these special tag comments can be placed. Thanks for the tip.
[asciidoc-diff.zip](https://github.com/mquinson/po4a/files/6615290/asciidoc-diff.zip)

**Comment by mquinson** [comment]
Hello all. @jnavila just commited a potential fix for this issue.

@eevan78, could you please confirm that this problem is fixed by the current git version? I'm confident since the patch was tested manually in the past, but please reopen this bug if it's not the case.

Thx,

**Comment by eevan78** [comment]
@mquinson, I have tried the current git version, and I can confirm that the fix is working as expected in my test files. Comments are passed through correctly.

Thanks!

**Comment by mquinson** [comment]
Please thank @jnavila for the hard work :)
And thanks for the confirmation.

**Comment by eevan78** [comment]
Of course, big thanks to @jnavila for solving the issue and pointing me to the right direction! 👏
