### ISSUE TITLE
AsciiDoc: comments are ignored, breaking markup

### ISSUE THREAD

**Issue by paususe** [mquinson/po4a#308]
Let's say you have something like this valid AsciiDoc in source.adoc:

```
some text in English
+
// COMMENT THAT WILL CONFUSE PO4A
+
more text in English
```

This is rendered by AsciiDoc as:

```
some text in English

more text in English
```

After AsciiDoc => gettext => AsciiDoc conversion, this is what you get:

```
some text in English
+
+
more text in English
```

Now there are two consecutive "+" signs, which AsciiDoc understands as "the first + sign is to join those lines 1 and 3 in the same paragraph, and I am asked to print the second + sign", so it renders like this:

```
some text in English
+ more text in English
```

I am attaching a full example.

[po4acomments.zip](https://github.com/mquinson/po4a/files/6724221/po4acomments.zip)

**Comment by jnavila** [comment]
It seems that comments management of Po4a does not follow the asciidoc "norm" according to asciidoctor. In the documentation of asciidoctor, it [is written](https://docs.asciidoctor.org/asciidoc/latest/comments/#comment-lines) that single line comments break the block structures, where as in Po4a tests, [a line comment does not split a paragraph](https://github.com/mquinson/po4a/blame/master/t/fmt/asciidoc/Comments.adoc#L14-19).

**Comment by jnavila** [comment]
In fact, I'm not even sure that the behavior is consistent between asciidoc and asciidoctor here.

**Comment by mquinson** [comment]
Hello all. @jnavila just commited a potential fix for this issue.

@paususe, could you please confirm that this problem is fixed by the current git version? 

Thx,

**Comment by mquinson** [comment]
@paususe do you think that we could close this bug, or is there any remaining issue?
@jnavila what's your feeling here?

Thanks to both of you,
Mt

**Comment by jnavila** [comment]
The changeset passed the modified unittests. But there may be some corner cases in the real world that were missed.

**Comment by mquinson** [comment]
If so, I think we can close this bug. @paususe feel free to reopen it on need, or to submit another one.

Thanks a lot,
