### ISSUE TITLE
keeping GitHub markdown styling

### ISSUE THREAD

**Issue by VietThan** [mquinson/po4a#309]
Hi, new user to po4a. I am looking for different translation maintenance tools and I was looking into po4a. So I used very simple po4a commands following the man pages suggestion:

```
po4a-gettextize -f text -m README.md -p README_vi.po -M UTF-8
```

and

```
po4a-translate -f text -m README.md -p README_vi.po -l README_vi.md -M UTF-8
```

I noticed that GitHub code block that is only one line doesn't keep the lines format correctly. I demonstrated that with this [test](https://github.com/VietThan/po4a-test/) (please look at how it's different in the Vietnamese translations). 

Is this expected behavior? Or is there something I'm missing when running the two commands above.

Best,

Viet

**Comment by mquinson** [comment]
Hello @VietThan, sorry for the extensive delay. This bug fall into the depths of my inbox.

are you still suffering from this bug? If so, you should first use the main po4a script, and not the po4a-* subscripts that are deprecated.

Then, I'd appreciate if you could help us debugging the issue by describing it. What do you think is the change induced by po4a that results in the visual change that you are experiencing?

Thanks for your help helping you ;)
Mt

**Comment by mquinson** [comment]
Hello, 

it seems to me that you are missing the `-o markdown` component on your command line, both with gettextize and translate. I'm rather sure that this is the reason of the behaviour that you were observing. Please feel free to reopen this bug if I'm wrong.

Thanks for reporting,
Mt
