### ISSUE TITLE
Travis no longer watches your back

### ISSUE THREAD

**Issue by jnavila** [mquinson/po4a#310]
Travis-ci.org is now dead, the CI no longer runs the tests.

I tried to run `./Build test` on a fresh checkout and the POD tests fail.

Time to move to GitHub actions...

**Comment by mquinson** [comment]
:weary: 

Ok, I do that. Thanks for noticing.

**Comment by mquinson** [comment]
Ok, I have a green build on github actions, and I get emails when the build is red. I hope it's not only when I am the one pushing the faulty commit, but that's a good start, I guess.

Thus closing. Thanks again for reporting.
