### ISSUE TITLE
excessive memory usage for building darktable documentation

### ISSUE THREAD

**Issue by darix** [mquinson/po4a#317]
running openSUSE Tumbleweed po4a 0.63 this uses 5-6GB of memory and feels a bit excessive. Is this really the expected amount?

```
git clone --recursive https://github.com/darktable-org/dtdocs.git dtdocs
cd dtdocs/
pushd themes/hugo-darktable-docs-theme/assets
yarn install
popd
cd tools
./generate-translations.sh --no-update
```

**Comment by jnavila** [comment]
Hello,

This can be related to #302.

What is your version of perl?

 If possible, could you try running with the master branch which includes a69b48e ?

JN

**Comment by darix** [comment]
5.32.1

i will build a po4a package with that patch in a moment

**Comment by darix** [comment]
thank you this helped.

fix for opensuse tumbleweed is on the way into the distribution https://build.opensuse.org/request/show/918048
