### ISSUE TITLE
po4a-gettextize stops at macro .it 1 an-trap

### ISSUE THREAD

**Issue by KBDCALLS** [mquinson/po4a#339]
po4a-gettextize stops at macro .it 1 an-trap

**po4a-gettextize -f man -m gitrevisions.7 -p gitrevisions.7.po  -o groff_code=verbatim**

gitrevisions.7:47: (po4a::man)
               Unbekanntes Makro ».it 1 an-trap«. Entfernen Sie es aus dem Dokument oder werfen Sie einen Blick in die 
               Handbuchseite von Locale::Po4a::Man, um herauszufinden, wie po4a mit neuen Makros umgehen kann.

gitrevisions.7:47: (po4a::man)
               Unknown macro '.it 1 an-trap'. Remove it from the document, or refer to the Locale::Po4a::Man manpage to 
               see how po4a can handle new macros.

**Comment by mquinson** [comment]
I've checked on the `.it` groff syntax (eg [here](https://www.gnu.org/software/groff/manual/groff.html#Input-Line-Traps) or [here](https://cmd.inp.nsk.su/old/cmd2/manuals/unix/UNIX_Unleashed/ch08.htm)) but I'm not sure I understand what it does. I think that we should leave the `.it 1 an-trap` line unmodified, but I'm not 100% sure.

If someone could confirm, I'd appreciate.

**Comment by jnavila** [comment]
Just a side question: why would you want to gettextize the manpage of gitrevisions in manpage format? The [source file](https://github.com/git/git/blob/master/Documentation/gitrevisions.txt) is written in asciidoc.

**Comment by mquinson** [comment]
I guess that this is to save a translation that was done by error on the groff page, so this is valid.

**Comment by jnavila** [comment]
I'm not questioning the validity of this request. I'm just intrigued, because trying to set up the git manpages translation project, I come across somebody else doing the same effort.

@KBDCALLS Could you refer to the project where you are facing this issue? That may help join effort. Thank you.

**Comment by mquinson** [comment]
@KBDCALLS could you please test if you get the expected behavior when adding `-o untranslated=it` ? According to the https://po4a.org/man/man3/Locale::Po4a::Man.3pm.php page, that should fix your problem.

**Comment by mquinson** [comment]
@KBDCALLS could you please report whether adding `-o untranslated=it` fixes the problem?
