### ISSUE TITLE
groff .ie, .el and .de are unknown

### ISSUE THREAD

**Issue by smoe** [mquinson/po4a#361]
Hello, I got
```
error: Skipping man/man1/io.1 with format po4a do not handle
error: 2:.de TQ
```
but https://www.gnu.org/software/groff/manual/html_node/Writing-Macros.html and https://www.gnu.org/software/groff/manual/html_node/if_002delse.html describe this code as valid.

Many thanks!

**Comment by mquinson** [comment]
Hello @smoe, thanks for reporting. Could you please tell me what I'm supposed to do with these macros? You could also try to add for example `-o untranslated=de` if it's OK to leave the `de` macro untranslated. If it's not to be untranslated, you can refer to https://po4a.org/man/man3/Locale::Po4a::Man.3pm.php and add the macros to the right set (one of `untranslated`, `noarg`, `translate_joined`, `translate_each`, `no_wrap` or `inline`).

Once you've found the set in which each macro belongs, please tell me, or provide a PR adding your new macros to Man.pm as the existing ones.

**Comment by mquinson** [comment]
Ok, found it, it's even easier than expected. Gime a second.

**Comment by mquinson** [comment]
I think it's fixed, in the sense that now po4a will output an error message hinting about the right option to handle these macros: `groff_code=translate` or `groff_code=verbatim`. @smoe do not hesitate to reopen and comment on need.
