### ISSUE TITLE
AsciiDoc: Hard line breaks are destroyed

### ISSUE THREAD

**Issue by oliverrahner** [mquinson/po4a#385]
Hard line breaks (https://docs.asciidoctor.org/asciidoc/latest/blocks/hard-line-breaks/) are not recognized during parsing.

A hard line break is recognizable by the three chars " +\n" in sequence. Because paragraphs have their intermediate line breaks removed, this will break, leaving us with only " + ", which leads to unfortunate output like this:

![image](https://user-images.githubusercontent.com/2277681/188821749-20cac3fb-9fbd-437e-9d96-7ca927c95b06.png)

as opposed to the original:

![image](https://user-images.githubusercontent.com/2277681/188821855-c3fe1740-9273-4f34-8ee1-60b3a15b418a.png)

**Comment by jnavila** [comment]
It is supported since version 0.67. If it does not work, please provide a minimal counter example.

**Comment by oliverrahner** [comment]
My mistake... turn out I had a mix of versions installed, one from a package repo and one as a git clone, that broke my files.
And when I checked for that implicitly, po4a didn't do anything because the po file seemed up to date :-/

In short: Everything works as I would expect now.
