### ISSUE TITLE
Support nested keys in yfm_keys (Markdown)

### ISSUE THREAD

**Issue by rtsisyk** [mquinson/po4a#392]
Thanks for the great tool. It would be nice to add support for nested keys for `--yfm_keys` option:

```
title: "My title"
extra:
  menu_title: Home <!-- not supported currently
```

I took a look at implementation, but the code is too complex for me to patch it quickly. Please help.

https://github.com/mquinson/po4a/blob/8279b57c1d56c4afdb04f551b7e0a55acddf2069/lib/Locale/Po4a/TransTractor.pm#L1291-L1343

**Comment by mquinson** [comment]
Hello,

I have the feeling that this can be achieved with `-o 'yfm_paths=extra menu_title'` (and my commits of earlier today). Could you please test whether it's doing what you want and tell us?

Thanks,
Mt

**Comment by mquinson** [comment]
I'm rather sure that my change is actually fixing your problem, so I'm closing this issue. Please feel free to reopen if I'm off track.
