### ISSUE TITLE
Disable Markdown wrapping

### ISSUE THREAD

**Issue by rtsisyk** [mquinson/po4a#399]
Would it be possible to disable Markdown wrapping at 80 characters? I haven't found an option...

**Comment by silopolis** [comment]
Would indeed be nice for projects using the one-sentence-per-line
formatting!

**Comment by mquinson** [comment]
Hello,

I think that you're looking for the `neverwrap` option of the Text module. You need to pass it as `-o markdown -o neverwrap`

I'm closing this issue because I think this is it. Please feel free to reopen if I misunderstood your request, of if a problem occurs.

Cheers,
Mt
