### ISSUE TITLE
latex: `\input` breaks when surrounded with {curly braces}

### ISSUE THREAD

**Issue by MayeulC** [mquinson/po4a#405]
Minimal reproducer (`main.tex`, with at least an empty `subfile.tex` next to it):

```
\documentclass{article} 
 
\begin{document} 
{\input{subfile.tex}}
\end{document}
```

See that `\input` is surrounded by curly braces. Compilation fails when that is the case, and succeeds otherwise.
As to why I need this: I use multiple `tikzpicture` graphs in `subcaptionbox` that I input from other files.

This is the (confusing) error:

```
Use of uninitialized value $newfilepath in string eq at /usr/share/perl5/vendor_perl/Locale/Po4a/TeX.pm line 998.
po4a::tex: Cannot find main.tex with kpsewhich
```

Even more confusingly, the exact same error is displayed when `subfile.tex` does not exist (with or without curly braces), and complains that the parent file cannot be found, while it's the included file that does not exist.

**Comment by MayeulC** [comment]
After testing some more, the issue comes from the following regex:

https://github.com/mquinson/po4a/blob/51f9008e7aa3803b76a2b8c7511c5c54dbdf8322/lib/Locale/Po4a/TeX.pm#L970-L972

Which matches the wrong filename (capture group 3), as `subfile.tex}` (including the curly bracket).

Including the curly bracket in the list of non-matching symbols seems to fix it, and it is highly unlikely to have this in a filename, especially when it comes to TeX source code, so I'll submit a PR.

**Comment by MayeulC** [comment]
I submitted a PR, but there is another issue (besides the error message that I should improve): `\input{subfile.pgf}` won't work with a `pgf` extension, weirdly (it works with other random extensions I tried). It displays the same error:

```
Use of uninitialized value $newfilepath in string eq at /usr/share/perl5/vendor_perl/Locale/Po4a/TeX.pm line 999.
po4a::tex: Cannot find main.tex with kpsewhich
```

I don't think I'll try to fix that one, I usually use the following snippet for including `pgf` plots anyway:

```tex
\newcommand{\importpgf}[2]{% see https://tex.stackexchange.com/a/640884 include from subfolders with \importpgf{figures/path}{img}
        \tikzsetnextfilename{pgf-#2}%
        \begin{tikzpicture}%
                \node[inner sep=0pt] {\import{#1}{#2.pgf}};
        \end{tikzpicture}
}
```

**Comment by mquinson** [comment]
Maybe the following patch fixes the confusing "Use of uninitialized value" part of the error message? Not tested at all.

```perl
--- a/lib/Locale/Po4a/TeX.pm
+++ b/lib/Locale/Po4a/TeX.pm
@@ -993,7 +993,7 @@ sub read_file {
 
                 # search the file
                 open( KPSEA, "kpsewhich " . $newfilename . " |" );
-                my $newfilepath = <KPSEA>;
+                my $newfilepath = <KPSEA> // ""; # Use an empty string if the content is undef
 
                 if ( $newfilename ne "" and $newfilepath eq "" ) {
                     die wrap_mod( "po4a::tex", dgettext( "po4a", "Cannot find %s with kpsewhich" ), $filename );
 ```

**Comment by MayeulC** [comment]
Possibly, I'll try that, thank you. It's my first time touching Perl code, though I am comfortable enough with regexes (and... they aren't the best tool for parsers).

I was thinking of checking if it was undef, and displaying an error message containing `$newfilename` instead of `$filename` because that's much more useful for the user.

Actually, maybe that's an oversight in the `die` expression below, and it should read something like `"Cannot find %s with kpsewhich, included from %s" ), $newfilename, $filename )` (not sure if multiple arguments need to be specified separately or in an array).

**Comment by mquinson** [comment]
You should post new messages, not edit the old ones : I don't get any notification per email when you edit your messages ;)

If you can prepare a PR, it'd be really appreciated as I'm somewhat overloaded these days. If not, I'll eventually do it at some point, but I feel less confident because testing po4a on latex is not 100% trivial for me right now.

**Comment by MayeulC** [comment]
> You should post new messages, not edit the old ones : I don't get any notification per email when you edit your messages ;)

Okay, I'll do that :)

I have a bit more time these days, I'll try to send another PR for the error message when I can.

**Comment by mquinson** [comment]
Thanks again for your contribution @MayeulC, and sorry I failed to merge your change for so long. Thanks to @lksj for the helping hand here.

**Comment by MayeulC** [comment]
No worries, I apologize for taking so long to come back to you with some tests. I didn't use po4a for a while, as I was focused on translating, but I could have done something this month :sweat_smile: 

I've had some success with po4a, though I had two other issues:
* TeX -> po4a -> TeX introduces some line breaks, which breaks things when they are in the wrong spots:
  * `\lstinline|do not break here|`
  * `\label{you-should-not-break-here}`
  * And various others. I would have been way more conservative about introducing line breaks.
* Possibly related? po4a tries to locate some files included with `\input`, but adds line breaks at the end of the filename. I hacked together an ugly workaround:

```diff
--- a/lib/Locale/Po4a/TeX.pm
+++ b/lib/Locale/Po4a/TeX.pm
@@ -958,7 +958,7 @@ sub read_file {
     my $charset = shift || 'UTF-8';
     my $linenum = 0;
     my @entries = ();
-
+    $filename =~ s/^(.*)\n*$/$1/gm;
     open( my $in, "<:encoding($charset)", $filename )
       or croak wrap_mod( "po4a::tex", dgettext( "po4a", "Cannot read from %s: %s" ), $filename, $! );
     while ( defined( my $textline = <$in> ) ) {
```

**Comment by mquinson** [comment]
Please try the current git version and add `--width=0` to the parameters you pass to your LaTeX files. Either on the po4a command line, or as an option of the command line.

It should disable the wrapping of the translated file. 

If it does not work, please open a new bug. Commenting in an already closed bug is a very very bad habit, I have to modify my workflow to not miss your info.

**Comment by MayeulC** [comment]
@mquinson Sorry again about that. I'll test some more, and open new issues/PRs as appropriate. Thank you for the tip.

I also found some tips about line wrapping in https://github.com/mquinson/po4a/issues/359, though I did not realize it would be an issue before finishing the translation, hence why I didn't search for this option before.

**Comment by mquinson** [comment]
Indeed, wrapping the translated file is probably a design error in po4a, as it does not bring any good while it makes the formating fragile. That is why I implemented width=0 this night. I may consider making this the default in the future to fix all formats at once.
Please report any potential issue
