### ISSUE TITLE
po4a dies on *.adocs with no translatable content

### ISSUE THREAD

**Issue by suddenfall** [mquinson/po4a#408]
I have a complex adoc-project with many includes. Some documents just contains includes. On these files po4a fails, because it cannot create a corresponding pot.

### My fix:
Adding the parameter  **--force-po** to the command **msggrep** in the file **po4a** at line 1617.

### Modified line:
my $cmd     = "msggrep$Config{_exe} $split_pot_files{$master_pot} -o $outfile $pot_filename --force-po";

**Comment by suddenfall** [comment]
I have never done this before. I hope that fit.

**Comment by jnavila** [comment]
Hello. You have to open a pull request to mquinson/po4a via the GitHub site in order for this change to be merged.
