### ISSUE TITLE
@AsciiDoc: Complete string is omitted

### ISSUE THREAD

**Issue by suddenfall** [mquinson/po4a#411]
The complete string is omitted, when two anchors [[...]] are used in the same line. I guess the corresponding regex is greedy but should not be greedy.

Here is an example to test it:
[bug2.zip](https://github.com/mquinson/po4a/files/11496615/bug2.zip)

**Comment by jnavila** [comment]
Ha. This one is wicked. The bug is only triggered if there are anchors at the beginning and the end of the line. Then, the line is mis-interpreted as a styling stanza.

Will propose a patch soon.

**Comment by jnavila** [comment]
BTW, thank you very much for the minimal reproducing set up. This is perfect for debugging!

**Comment by suddenfall** [comment]
I'm also an engineer and author of a few tiny open source projects. I know that a good bug report is half the bug fix.
