### ISSUE TITLE
[feature] vim help format

### ISSUE THREAD

**Issue by Freed-Wu** [mquinson/po4a#418]
The examples of vim help format: <https://github.com/vim/vim/blob/master/runtime/doc/helphelp.txt> <https://github.com/yianwillis/vimcdoc/blob/master/doc/helphelp.cnx>

TIA!

**Comment by jnavila** [comment]
Try first with the text mode of po4a and see if there are special cases.

**Comment by mquinson** [comment]
I agree with @jnavila. This file should be handled fine with the text module of po4a. I'm thus closing this report, but feel free to open new ones if you have a specific issue while translating these files.

Thanks for the report, and happy translating.

**Comment by Freed-Wu** [comment]
OK, I'll try. I have discussed with the author of vimcdoc about the possiblity of use po4a to translate vim doc. Thanks!.

**Comment by Freed-Wu** [comment]
Something need to be improved, such as `===...` and `---...` is first level header and second level header of vim help. However, whatever text and markdown cannot support it well.

```po
#. type: Plain text
#: /usr/share/nvim/runtime/doc/help.txt:41
#, fuzzy, markdown-text, no-wrap
msgid "==============================================================================\n"
msgstr "==============================================================================\n"
```

And vim modeline shouldn't be translated:

```po
#. type: Plain text
#: /usr/share/nvim/runtime/doc/help.txt:201
#, fuzzy, markdown-text, no-wrap
msgid " vim:tw=78:isk=!-~,^*,^\\|,^\\\":ts=8:noet:ft=help:norl:\n"
msgstr " vim:tw=78:isk=!-~,^*,^\\|,^\\\":ts=8:noet:ft=help:norl:\n"
```
