### ISSUE TITLE
Ambiguity in license statement

### ISSUE THREAD

**Issue by steffenb7333** [mquinson/po4a#434]
Could you explicitly state if by "This program is free software; you may redistribute it and/or modify it under the terms of GPL (see COPYING file)" you mean [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html) or [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html)? This question came up during a bug-report and I think that ambiguity in the phrasing can only be resolved by you, though I currently understand it is as GPL-2.0-only.

**Comment by berrange** [comment]
I'm looking for the same answer as part of converting Fedora  to SPDX identifiers.

Both the README file and the blurb at the top of most files are imprecise in merely saying GPL and pointing to the COPYING file - the latter actually says that each source file must add a header where you would either keep or remove the "or later" clause.

I note that Debian took the view that it was 2.0-or-later https://salsa.debian.org/debian/po4a/-/blob/master/debian/copyright  but I think it ought to be stated explicitly in upstream. For now I'm going to follow Debian's lead and assume 2.0-or-later

**Comment by jnavila** [comment]
Hello,

The main developer of this project being also the debian packager, we can assume that the license is GPL2+.

**Comment by mquinson** [comment]
Hello,

sorry for the delay. The intend is indeed GPL2+. How should I change things to make this explicit?

Thanks,

**Comment by jnavila** [comment]
I guess adding a correct header to all source files is required.

**Comment by berrange** [comment]
> sorry for the delay. The intend is indeed GPL2+. How should I change things to make this explicit?

The bare minimum would be to change the README.md file line about licensing to explicitly state the version, as that would make it unambiguous when looking at the project as a whole.

The ideal would be to do the same for each source file too, to make it unambiguous when someone has just a single source file in isolation.
