### ISSUE TITLE
Opinion Sought

### ISSUE THREAD

**Issue by bexelbie** [mquinson/po4a#44]
I am looking at making some changes to AsciiDoc parsing and adding a Yaml parser.  Both of these formats may have modules in CPAN that support them or other tooling that could be used.

What is our opinion of introducing either additional perl or non-perl depdencies?

For example, Yaml::XS requires a C-library.  Asciidoctor is ... well asciidoctor and could be a dependency.

**Comment by mquinson** [comment]
Hello, thanks for all this.

The most important thing to me is that po4a remains easily in Debian. If you add a dependency that is properly packaged in Debian, then that's fine to me. But I don't feel like packaging other perl packages for po4a. 

Of course, we could also use tricks to disable AsciiDoc when the dependencies are not there, but it feels quite complex so we need a real motivation for this.

Thanks for your time,
Mt

**Comment by bexelbie** [comment]
Fair point. Thank you. I'll leave this open waiting on me to figure out my likely dependency needs I agree that selective disabling is less than ideal. I'd also like to not have to add packages to Fedora for the same reason.

**Comment by bexelbie** [comment]
I'd still like to shift toward a more canonical parser in some cases, however that is more relevant to the code refactor discussion.  Closing.
