### ISSUE TITLE
Feature request for AsciiDoc:  Translate tables by line

### ISSUE THREAD

**Issue by boydkelly** [mquinson/po4a#441]
Thanks for the amazing work done here.   This is not an essential, but maybe nice to have if it could be implemented at some point.

Currently the the -o tablecells option a translator has the option of translating table data by cell or by the entire table.  While dealing with a rather complicated table recently I was thinking it would be nice to have a tablelines option as well.   Just a thought!  I think it would be very practical.

Thank you!

**Comment by jnavila** [comment]
Ah, quite unexpected... I'm not sure that this is easy to handle, because you need to interpret the formatting grammar of Asciidoc cells in order to define which cells start a new line (due to horizontal spanning). Also, for vertical spanning, how to you define a line?

**Comment by boydkelly** [comment]
Yes I can totally see that issue.   Not a huge problem.  Just an idea.  Merci pour l'excellent travail ici!

**Comment by mquinson** [comment]
Hello, as noted by @jnavila, translating tables by line is probably cumbersome, as the translator must respect the formating anyway. I would advise not to do so, and thus close the bug.

@boydkelly if you disagree and have a real use case, please feel free to reopen the bug and comment.
