### ISSUE TITLE
Typo in po4a doc

### ISSUE THREAD

**Issue by rffontenelle** [mquinson/po4a#471]
https://github.com/mquinson/po4a/blob/fb33e886dee4074faa4dacf3d24f0b50f4560c3a/po4a#L111-L112

The text should probably be "It specifies that all PO files (...) are **in** the man/po4a/ directory". I'll leave for confirmation before presenting any pull request.

**Comment by mquinson** [comment]
Indeed, that's the intend, good catch. PR welcome :)

**Comment by rffontenelle** [comment]
Thanks for the reply. I'm updating pt_BR translation and as soon as I finish it, I'll send a PR
