### ISSUE TITLE
How to generate Markdown without line wrap?

### ISSUE THREAD

**Issue by rffontenelle** [mquinson/po4a#474]
I have a Markdown file as master doc that has long lines. I would like to generate the translated doc with these long lines, instead of having them wrapped in +/- 75 characters per line.

Adding the `-o neverwrap` option causes the PO file to have all strings with `no-wrap` flag and with a trailing new-line `\n` character. I'd prefer to not have the translation strings without the `no-wrap` flag and without the trailing new-line character.

Is there an alternative?

**Comment by Fat-Zer** [comment]
As far as I can see, as for now there is no way to do it.

It seems, it was supposed to be controlled by `po4a-translate`'s `--width` option, but it was never actually implemented.

**Comment by jnavila** [comment]
This was raised (#242) and implemented (0bf9652) in Asciidoc, by removing the carriage return after the fact... This request is understandable, as, just like Asciidoc, Markdown may encounter mis-formatting issues due to unlucky line-wrapping.
