### ISSUE TITLE
second argument to Locale::Po4a::TransTractor::read now mandatory

### ISSUE THREAD

**Issue by jmtd** [mquinson/po4a#504]
The docs for `Locale::Po4a::TransTractor::read` suggest it takes two arguments, the second of which is optional.

This commit added a third optional argument (which is not documented, at least in the manpage):

https://github.com/mquinson/po4a/commit/697fbbc2ad631f9682376a221dcefd37a734a944

It also made the second argument mandatory, possibly by accident.

This has started to break various Debian packages.

**Comment by mquinson** [comment]
Hello,

I had simply no idea that this code was used directly out of po4a. I could never imagine this, actually. I'll fix the manpage, but you should indeed fix the calling code to pass a refname (it can be the filename, it's what will be used to build the references in po files) and a charset (UTF-8 is probably a good value).

Would it work for you?

**Comment by mquinson** [comment]
Actually, the charset is still optionnal
