### ISSUE TITLE
PO validity check for 0.52 breaks on Windows

### ISSUE THREAD

**Issue by Elberet** [mquinson/po4a#65]
During my evaluation of po4a 0.52 I've encountered a regression over 0.51, possibly introduced in 1107d64 in [lib/Locale/Po4a/Po.pm:258](https://github.com/mquinson/po4a/commit/1107d64d0f411194affb890ad361bd950b4b4fdb#diff-4209cbaea73ae45d2406625ec02829dcR258). When running e.g. `po4a-translate` through Strawberry Perl on Windows, the command in `$cmd` is eventually passed to `cmd.exe` which doesn't understand the POSIX-style environment variable declaration. The result is a message such as this:

```
Invalid po file doc/src/some/file.po:
'LC_ALL' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mquinson** [comment]
Hello, 
sorry for my crude hack here. We should use the standard perl way of adding a variable to the environment, without relying on a shell to execute our commands.

**Comment by Elberet** [comment]
Thanks for taking the time to fix this... but see https://github.com/mquinson/po4a/commit/1529c55c901fca705ea65d2a374dd03ea7eb3931#r29919692 - as it is now, the child process is run without an adjusted `LC_ALL`.

**Comment by mquinson** [comment]
Thanks for noticing. I hope it's OK now...
