### ISSUE TITLE
Key/Value Pairs should be treated as verbatim

### ISSUE THREAD

**Issue by bexelbie** [mquinson/po4a#8]
Many static site generators, amongst other things, require a set of header information at the top of the file such as:

```
Title: Some title
Date: Some date

lorem ipsum ...

foo bar baz ...
```

We should be able to optionally allow any paragraph formatted as key:value to be treated as verbatim.  I have a potential fix (needs tests) here: https://github.com/bexelbie/po4a/tree/keyvalue_text

**Comment by Jibec** [comment]
works fine for me, thank you Brian

**Comment by mquinson** [comment]
A pull request with these changes (and some basic testing) would be gratefully integrated...

Thanks in advance, Mt
